# Hand-written -- NOT autogenerated. Track B step 5: state-only relocation of
# TeacherLeave, LongTermReliefAssignment, and TeacherStructuralAvailability
# into the `staff` app. database_operations is empty, so this issues zero
# SQL -- it only tells Django's migration state that these three models now
# belong to `staff`. The physical tables (pinned via Meta.db_table in
# apps/staff/models.py) never move. The exact CreateModel field reprs below
# were taken verbatim from
# `manage.py makemigrations students staff school --dry-run -v3` -- Django's
# own autodetector, not hand-transcribed -- to guarantee zero drift against
# `makemigrations --check`. Paired with
# school/migrations/0095_move_students_staff_models_to_apps.py, which deletes
# the same three models from `school`'s state, also with
# database_operations=[].
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0095_move_students_staff_models_to_apps'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='TeacherLeave',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('leave_type', models.CharField(choices=[('Casual', 'Casual Leave'), ('Sick', 'Medical/Sick Leave'), ('Maternity', 'Maternity/Paternity Leave'), ('Seminar', 'Official Duty / Seminar'), ('Compassionate', 'Compassionate Leave')], max_length=20)),
                        ('start_date', models.DateField(help_text='First day of leave.')),
                        ('end_date', models.DateField(help_text='Last day of leave (inclusive).')),
                        ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=15)),
                        ('reason', models.TextField(blank=True, help_text='Optional context notes.', null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='school.teacherextra')),
                    ],
                    options={
                        'db_table': 'school_teacherleave',
                        'ordering': ['-start_date'],
                    },
                ),
                migrations.CreateModel(
                    name='LongTermReliefAssignment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('start_date', models.DateField()),
                        ('end_date', models.DateField()),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('absent_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relief_covers_needed', to='school.teacherextra')),
                        ('relief_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relief_covers_provided', to='school.teacherextra')),
                        ('associated_leave', models.OneToOneField(help_text='Links directly to an approved long-term leave instance.', limit_choices_to={'status': 'Approved'}, on_delete=django.db.models.deletion.CASCADE, to='staff.teacherleave')),
                    ],
                    options={
                        'db_table': 'school_longtermreliefassignment',
                        'unique_together': {('absent_teacher', 'start_date', 'end_date')},
                    },
                ),
                migrations.CreateModel(
                    name='TeacherStructuralAvailability',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('reason', models.CharField(blank=True, help_text="e.g., 'HOD Meeting', 'Part-time off-day'", max_length=100, null=True)),
                        ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_slots', to='school.teacherextra')),
                        ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.timeslot')),
                    ],
                    options={
                        'db_table': 'school_teacherstructuralavailability',
                        'unique_together': {('teacher', 'time_slot')},
                    },
                ),
            ],
        ),
    ]
