# Generated by Django 6.0.1 on 2026-08-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_permission_adminextra_admininvitecode_and_more'),
        ('staff', '0002_alter_teacherstructuralavailability_time_slot'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='longtermreliefassignment',
                    name='absent_teacher',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relief_covers_needed', to='identity.teacherextra'),
                ),
                migrations.AlterField(
                    model_name='longtermreliefassignment',
                    name='relief_teacher',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relief_covers_provided', to='identity.teacherextra'),
                ),
                migrations.AlterField(
                    model_name='teacherleave',
                    name='teacher',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='identity.teacherextra'),
                ),
                migrations.AlterField(
                    model_name='teacherstructuralavailability',
                    name='teacher',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_slots', to='identity.teacherextra'),
                ),
            ],
            database_operations=[]
        )
    ]
