# Generated by Django 6.0.7 on 2026-09-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_teacherleave_deleted_at_teacherleave_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherleave',
            name='leave_type',
            field=models.CharField(choices=[('Casual', 'Casual Leave'), ('Sick', 'Medical/Sick Leave'), ('Maternity', 'Maternity/Paternity Leave'), ('Seminar', 'Official Duty / Seminar'), ('Compassionate', 'Compassionate Leave')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherleave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=15),
        ),
    ]
