# Generated by Django 6.0.1 on 2026-09-22 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0009_alter_adminextra_mobile_alter_adminextra_status_and_more'),
        ('staff', '0005_alter_teacherleave_leave_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherleave',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='identity.staffextra'),
        ),
        migrations.AlterField(
            model_name='teacherleave',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='identity.teacherextra'),
        ),
        migrations.AddConstraint(
            model_name='teacherleave',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('staff__isnull', True), ('teacher__isnull', False)), models.Q(('staff__isnull', False), ('teacher__isnull', True)), _connector='OR'), name='teacherleave_exactly_one_applicant'),
        ),
    ]
