# Hand-written -- NOT autogenerated. Track B step 6: state-only relocation of
# GlobalAllocationPolicy, AllocationPublishState, QuotaDefaultRule,
# SubjectAllocation, SubjectBlock, SubjectQuota, and SubjectSplittingRule
# into the `allocations` app. database_operations is empty, so this issues
# zero SQL -- it only tells Django's migration state that these seven models
# now belong to `allocations`. The physical tables (pinned via Meta.db_table
# in apps/allocations/models.py) never move, including the
# `school_subjectblock_subjects` M2M join table (pinned via db_table= on the
# field itself). The exact CreateModel field reprs below were taken verbatim
# from `manage.py makemigrations allocations timetable school --dry-run -v3`
# -- Django's own autodetector, not hand-transcribed -- to guarantee zero
# drift against `makemigrations --check`. Paired with
# school/migrations/0096_move_allocations_timetable_models_to_apps.py, which
# deletes the same seven models from `school`'s state, also with
# database_operations=[].
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0096_move_allocations_timetable_models_to_apps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='GlobalAllocationPolicy',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('max_subjects_per_class', models.PositiveIntegerField(default=2)),
                        ('max_classes_per_subject', models.PositiveIntegerField(default=2)),
                        ('min_classes_per_subject', models.PositiveIntegerField(default=2, help_text='Target minimum streams a teacher should handle for a subject to optimize prep time.')),
                        ('enforce_prep_consolidation', models.BooleanField(default=True, help_text='If True, the auto-drafter will magnetically prioritize teachers sitting below the minimum stream count.')),
                        ('allow_cross_grade_teaching', models.BooleanField(default=False)),
                        ('max_weekly_lessons', models.PositiveIntegerField(default=28, help_text='Total teaching periods allowed per week.')),
                        ('max_total_class_groups', models.PositiveIntegerField(default=6, help_text='Max distinct physical/virtual groups a teacher can manage.')),
                        ('timetable_capacity_buffer_percent', models.PositiveIntegerField(default=10, help_text="Safety margin subtracted from a teacher's real free-slot count (total time slots minus their structural blackouts) before the allocation engine will assign them more lessons. Fatigue rules (consecutive-period caps, heavy-day thresholds, subject spacing) aren't modeled here, so this buffer accounts for the usable capacity they eat into that a raw slot count alone wouldn't show.")),
                        ('enforcement_mode', models.CharField(choices=[('STRICT', 'Strict Hard Blocks (Prevent Saves)'), ('SOFT', 'Soft Enforcement (Allow Saves with Warnings)')], default='STRICT', max_length=10)),
                    ],
                    options={
                        'db_table': 'school_globalallocationpolicy',
                    },
                ),
                migrations.CreateModel(
                    name='AllocationPublishState',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('is_published', models.BooleanField(default=False)),
                        ('published_at', models.DateTimeField(blank=True, null=True)),
                        ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear')),
                        ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_states', to='school.classstream')),
                        ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_allocations', to=settings.AUTH_USER_MODEL)),
                        ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.examterm')),
                    ],
                    options={
                        'db_table': 'school_allocationpublishstate',
                        'unique_together': {('classroom', 'term', 'academic_year')},
                    },
                ),
                migrations.CreateModel(
                    name='QuotaDefaultRule',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('grade_band', models.CharField(choices=[('LOWER_PRIMARY', 'Lower Primary (Grades 1-3)'), ('UPPER_PRIMARY', 'Upper Primary (Grades 4-6)'), ('JUNIOR_SECONDARY', 'Junior Secondary (Grades 7-9)'), ('SENIOR_SCHOOL', 'Senior School (Grade 10+)')], max_length=20)),
                        ('applies_when_blocked', models.BooleanField(default=False, help_text='Check for the figures that apply when the subject sits in a synchronized SubjectBlock for this grade (e.g. Technical/elective option blocks) — leave unchecked for the standalone-subject figures.')),
                        ('total_lessons', models.PositiveIntegerField(default=0)),
                        ('double_lessons_required', models.PositiveIntegerField(default=0)),
                        ('remedial_lessons_required', models.PositiveIntegerField(default=1)),
                        ('department', models.ForeignKey(blank=True, help_text="Leave blank to apply to any department — used for the blocked/synchronized-elective defaults, which don't vary by department. Set a specific department for a standalone-subject default.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quota_default_rules', to='school.department')),
                    ],
                    options={
                        'db_table': 'school_quotadefaultrule',
                        'ordering': ['department', 'grade_band'],
                        'unique_together': {('department', 'grade_band', 'applies_when_blocked')},
                    },
                ),
                migrations.CreateModel(
                    name='SubjectAllocation',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('is_active', models.BooleanField(default=True)),
                        ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear')),
                        ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='school.classstream')),
                        ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_allocations', to='school.subject')),
                        ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='school.teacherextra')),
                        ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.examterm')),
                    ],
                    options={
                        'db_table': 'school_subjectallocation',
                        'unique_together': {('classroom', 'subject', 'academic_year', 'term')},
                    },
                ),
                migrations.CreateModel(
                    name='SubjectBlock',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(help_text='e.g., G10-Humanities-Block or Form 3 Technical Electives', max_length=100)),
                        ('period_structure', models.CharField(choices=[('ALL_DOUBLE', 'All Double Periods'), ('ALL_SINGLE', 'All Single Periods'), ('MIXED', 'Mixed (Each Subject Uses Its Own Quota Split)')], default='MIXED', help_text="Governs how the quota/timetable engines split this block's lessons between single and double periods — e.g. Technical option blocks are usually ALL_DOUBLE (practical sessions), while a Humanities block is usually ALL_SINGLE.", max_length=10)),
                        ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                        ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                        ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_blocks', to='school.academicyear')),
                        ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_blocks', to='school.gradelevel')),
                        ('subjects', models.ManyToManyField(blank=True, db_table='school_subjectblock_subjects', related_name='blocks', to='school.subject')),
                        ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_blocks', to='school.examterm')),
                    ],
                    options={
                        'db_table': 'school_subjectblock',
                        'unique_together': {('name', 'grade_level', 'academic_year', 'term')},
                    },
                ),
                migrations.CreateModel(
                    name='SubjectQuota',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('total_lessons', models.PositiveIntegerField(default=5)),
                        ('double_lessons_required', models.PositiveIntegerField(default=0)),
                        ('remedial_lessons_required', models.PositiveIntegerField(default=1)),
                        ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_quotas', to='school.gradelevel')),
                        ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
                    ],
                    options={
                        'db_table': 'school_subjectquota',
                        'unique_together': {('grade', 'subject')},
                    },
                ),
                migrations.CreateModel(
                    name='SubjectSplittingRule',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('max_class_size', models.PositiveIntegerField(default=45, help_text='Max students per teacher before a split.')),
                        ('allocation_mode', models.CharField(choices=[('Split_Balance', 'Auto-Split & Balance Streams'), ('Co_Teaching', 'Co-Teaching (Single Massive Group)'), ('Strict_Cap', 'Strict Enrollment Cap')], default='Split_Balance', max_length=20)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splitting_rules', to='school.gradelevel')),
                        ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                        ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splitting_rules', to='school.subject')),
                    ],
                    options={
                        'db_table': 'school_subjectsplittingrule',
                        'unique_together': {('grade', 'subject')},
                    },
                ),
            ],
        ),
    ]
