# Hand-written -- NOT autogenerated. Track B step 8 side-effect: this app's
# FK fields already pointed at GradeLevel/Subject/Department/ClassStream/
# AcademicYear/ExamTerm (now app-label-string references, see
# apps/allocations/models.py), so their recorded migration `to=` app_label
# needs updating from `school.<model>` to `academics.<model>` now that those
# models physically moved. database_operations is empty -- an AlterField
# that only changes `to=`'s app_label (never the physical column/table/
# constraint, since Meta.db_table pins every table name) issues zero SQL.
# Every operation below was taken verbatim from
# `manage.py makemigrations academics --dry-run -v3` (which computes the
# full ripple across every app referencing a relocating model in one pass),
# not hand-guessed.
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='allocationpublishstate',
                    name='academic_year',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
                ),
                migrations.AlterField(
                    model_name='allocationpublishstate',
                    name='classroom',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_states', to='academics.classstream'),
                ),
                migrations.AlterField(
                    model_name='allocationpublishstate',
                    name='term',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.examterm'),
                ),
                migrations.AlterField(
                    model_name='quotadefaultrule',
                    name='department',
                    field=models.ForeignKey(blank=True, help_text="Leave blank to apply to any department — used for the blocked/synchronized-elective defaults, which don't vary by department. Set a specific department for a standalone-subject default.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quota_default_rules', to='academics.department'),
                ),
                migrations.AlterField(
                    model_name='subjectallocation',
                    name='academic_year',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
                ),
                migrations.AlterField(
                    model_name='subjectallocation',
                    name='classroom',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='academics.classstream'),
                ),
                migrations.AlterField(
                    model_name='subjectallocation',
                    name='subject',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_allocations', to='academics.subject'),
                ),
                migrations.AlterField(
                    model_name='subjectallocation',
                    name='term',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.examterm'),
                ),
                migrations.AlterField(
                    model_name='subjectblock',
                    name='academic_year',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_blocks', to='academics.academicyear'),
                ),
                migrations.AlterField(
                    model_name='subjectblock',
                    name='grade_level',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_blocks', to='academics.gradelevel'),
                ),
                migrations.AlterField(
                    model_name='subjectblock',
                    name='subjects',
                    field=models.ManyToManyField(blank=True, db_table='school_subjectblock_subjects', related_name='blocks', to='academics.subject'),
                ),
                migrations.AlterField(
                    model_name='subjectblock',
                    name='term',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_blocks', to='academics.examterm'),
                ),
                migrations.AlterField(
                    model_name='subjectquota',
                    name='grade',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_quotas', to='academics.gradelevel'),
                ),
                migrations.AlterField(
                    model_name='subjectquota',
                    name='subject',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
                ),
                migrations.AlterField(
                    model_name='subjectsplittingrule',
                    name='grade',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splitting_rules', to='academics.gradelevel'),
                ),
                migrations.AlterField(
                    model_name='subjectsplittingrule',
                    name='subject',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splitting_rules', to='academics.subject'),
                ),
            ],
        ),
    ]
