# Generated by Django 6.0.1 on 2026-08-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0002_alter_allocationpublishstate_academic_year_and_more'),
        ('identity', '0002_permission_adminextra_admininvitecode_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='subjectallocation',
                    name='teacher',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='identity.teacherextra'),
                ),
            ],
            database_operations=[]
        )
    ]
