# Generated by Django 6.0.7 on 2026-09-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0003_alter_subjectallocation_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationpublishstate',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='subjectallocation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
