# Generated by Django 6.0.1 on 2026-09-23 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_academicyear_is_active_and_more'),
        ('allocations', '0004_alter_allocationpublishstate_is_published_and_more'),
    ]

    operations = [
        # The live database has no unique constraint at all on
        # (department_id, grade_band, applies_when_blocked) today (confirmed via a read-only
        # pg_constraint query), even though the model history says it should -- a state/schema
        # mismatch inherited from how QuotaDefaultRule was relocated into this app via a
        # SeparateDatabaseAndState (state-only) migration. A plain AlterUniqueTogether still
        # diffs against that OLD (nonexistent) constraint no matter how it's arranged in this
        # file, so this state-only step tells Django's migration history "there's nothing there
        # to drop" without touching the real database -- the same SeparateDatabaseAndState
        # pattern already used throughout this app's own relocation history.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='quotadefaultrule',
                    unique_together=set(),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='quotadefaultrule',
            name='tier',
            field=models.ForeignKey(blank=True, help_text='Match this rule to a specific curriculum tier instead of the legacy grade_band bucket below. Leave blank to fall back to grade_band matching (legacy behavior).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quota_default_rules', to='academics.tier'),
        ),
        migrations.AddField(
            model_name='quotadefaultrule',
            name='trim_priority',
            field=models.PositiveSmallIntegerField(default=2, help_text="0 = protected longest (cut last) ... 3 = cut first, when Auto-Fill Subject Quotas has to trim a grade's demand down to fit the week's available capacity."),
        ),
        migrations.AlterUniqueTogether(
            name='quotadefaultrule',
            unique_together={('department', 'tier', 'grade_band', 'applies_when_blocked')},
        ),
    ]
