// ==========================================
// 1. FIREBASE: THE REAL-TIME MESSAGES
// ==========================================
// This exactly matches the rules we wrote in Firestore Security Rules
export interface IFirebaseMessage {
  id?: string; // The Firestore document ID (optional before it's saved)
  sender_email: string; // The VIP check
  message_body: string; // Max 2000 chars
  attachment_url?: string; // Optional file upload
  sent_at: number; // Unix timestamp for the 2-hour math check
}

// ==========================================
// 2. DJANGO: THE DIRECTORY SEARCH API
// ==========================================
// Matches the response from `GET /api/chat/search/`
export interface IUserSearchResult {
  user_id: number;
  name: string;
  role: "Admin" | "Teacher" | "Parent";
  email: string;
}

// ==========================================
// 3. DJANGO: THE ROOM GENERATOR API
// ==========================================
// Matches the response from `POST /api/chat/direct/` and `POST /api/chat/admin/group/`
export interface IRoomCreationResponse {
  thread_id: string; // The UUID generated by Postgres
  is_new?: boolean; // True if just created, false if existing (1-on-1 only)
  target_name?: string; // The name of the person/group we are messaging
  thread_type?: "Direct" | "Group" | "Broadcast"; 
  participant_count?: number; // Used for groups
}

// ==========================================
// 4. DJANGO: THE INBOX API
// ==========================================
// Matches the response from `GET /api/chat/inbox/`
export interface IInboxThread {
  thread_id: string; // The UUID
  chat_name: string; // e.g., "John Doe (re: Sarah)" or "Broadcast (45 members)"
  type: "Direct" | "Group" | "Broadcast";
  updated_at: string; // ISO DateTime string for sorting
  has_unread: boolean; // Powers the red dot notification
}

// ==========================================
// 5. DJANGO: THE ADMIN AUDIT VIEWER API
// ==========================================
// Matches the response from `GET /api/chat/admin/audit/<thread_id>/`
export interface IAuditLog {
  audit_id: number;
  firebase_id: string;
  sender_email: string;
  sender_name: string;
  message_body: string;
  attachment_url: string | null;
  is_urgent: boolean;
  sent_at: string; // ISO DateTime string
  synced_at: string; // ISO DateTime string
}