// ==========================================
// 1. DJANGO CHANNELS: THE REAL-TIME MESSAGES
// ==========================================
// Matches ChatConsumer/serialize_message_audit's wire format (school/views/chat_views.py)
export interface IMessage {
  id: number;
  thread_id: string;
  sender_id: number | null;
  sender_name: string;
  sender_role: string | null;
  message_body: string;
  attachment_url?: string | null;
  attachment_name?: string | null;
  is_actionable: boolean;
  is_urgent: boolean;
  is_edited: boolean;
  is_deleted: boolean;
  sent_at: string; // ISO DateTime string
  updated_at: string; // ISO DateTime string
}

// ==========================================
// 2. DJANGO: THE DIRECTORY SEARCH API
// ==========================================
// Matches the response from `GET /api/chat/search/`
export interface IUserSearchResult {
  user_id: number;
  name: string;
  role: "Admin" | "Teacher" | "Parent";
  email: string;
}

// ==========================================
// 3. DJANGO: THE ROOM GENERATOR API
// ==========================================
// Matches the response from `POST /api/chat/direct/` and `POST /api/chat/admin/group/`
export interface IRoomCreationResponse {
  thread_id: string; // The UUID generated by Postgres
  is_new?: boolean; // True if just created, false if existing (1-on-1 only)
  target_name?: string; // The name of the person/group we are messaging
  thread_type?: "Direct" | "Group" | "Broadcast"; 
  participant_count?: number; // Used for groups
}

// ==========================================
// 4. DJANGO: THE INBOX API
// ==========================================
// Matches the response from `GET /api/chat/inbox/`
export interface IInboxThread {
  thread_id: string; // The UUID
  chat_name: string; // e.g., "John Doe (re: Sarah)" or "Broadcast (45 members)"
  type: "Direct" | "Group" | "Broadcast";
  updated_at: string; // ISO DateTime string for sorting
  has_unread: boolean; // Powers the red dot notification
  last_message: string | null; // Preview text, e.g. "You: hey there" — null for empty threads
}

// ==========================================
// 6. DJANGO: THE PARTICIPANTS ROSTER API
// ==========================================
// Matches the response from `GET /api/chat/participants/<thread_id>/`
export interface IParticipant {
  user_id: number;
  name: string;
  role: string;
}

// ==========================================
// 5. DJANGO: THE ADMIN AUDIT VIEWER API
// ==========================================
// Matches the response from `GET /api/chat/admin/audit/<thread_id>/`
export interface IAuditLog {
  audit_id: number;
  sender_email: string;
  sender_name: string;
  message_body: string;
  attachment_url: string | null;
  is_urgent: boolean;
  sent_at: string; // ISO DateTime string
  synced_at: string; // ISO DateTime string
}