# Hand-written -- NOT autogenerated. Track B step 3: state-only relocation of
# Notice, Event, Notification, ChatUserProfile, ChatThread, ThreadParticipant,
# MessageAudit, and ChatActionResponse into the `messaging` app.
# database_operations is empty in every SeparateDatabaseAndState wrapper
# below, so this migration issues zero SQL -- it only tells Django's
# migration state that these eight models now belong to `messaging`. The
# physical tables (pinned via Meta.db_table in apps/messaging/models.py)
# never move. The exact CreateModel field reprs below were taken verbatim
# from `manage.py makemigrations messaging school --dry-run -v 3` -- Django's
# own autodetector, not hand-transcribed -- to guarantee zero drift against
# `makemigrations --check`. Paired with
# school/migrations/0093_move_messaging_models_to_apps_messaging.py, which
# deletes the same eight models from `school`'s state, also with
# database_operations=[].
import uuid

import django.db.models.deletion
import school.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0093_move_messaging_models_to_apps_messaging'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Event',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=200)),
                        ('description', models.TextField(blank=True, null=True)),
                        ('start_time', models.DateTimeField()),
                        ('end_time', models.DateTimeField()),
                        ('event_type', models.CharField(default='General', max_length=50)),
                        ('is_active', models.BooleanField(default=True)),
                    ],
                    options={
                        'db_table': 'school_event',
                    },
                ),
                migrations.CreateModel(
                    name='Notice',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(default='General Notice', max_length=200)),
                        ('message', models.TextField()),
                        ('date', models.DateField(auto_now_add=True)),
                        ('by', models.CharField(default='School Admin', max_length=50)),
                        ('audience', models.CharField(choices=[('All', 'All'), ('Teachers', 'Teachers Only'), ('Parents', 'Parents Only'), ('Students', 'Students Only')], default='All', max_length=20)),
                        ('attachment', models.FileField(blank=True, null=True, upload_to='notices/', validators=[school.validators.safe_document_validator])),
                        ('is_urgent', models.BooleanField(default=False)),
                    ],
                    options={
                        'db_table': 'school_notice',
                    },
                ),
                migrations.CreateModel(
                    name='ChatThread',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('thread_type', models.CharField(choices=[('Direct', '1-on-1 Direct Message'), ('Broadcast', 'One-way Broadcast (Admin to Many)'), ('Group', 'Group Chat')], default='Direct', max_length=20)),
                        ('is_active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_threads', to='school.studentextra')),
                    ],
                    options={
                        'db_table': 'school_chatthread',
                    },
                ),
                migrations.CreateModel(
                    name='ChatUserProfile',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('working_hours_start', models.TimeField(blank=True, null=True)),
                        ('working_hours_end', models.TimeField(blank=True, null=True)),
                        ('auto_reply_enabled', models.BooleanField(default=True)),
                        ('auto_reply_message', models.CharField(default='I am currently offline. I will respond during standard school working hours.', max_length=255)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_profile', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'school_chatuserprofile',
                    },
                ),
                migrations.CreateModel(
                    name='MessageAudit',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('message_body', models.TextField()),
                        ('attachment_url', models.URLField(blank=True, max_length=1000, null=True)),
                        ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                        ('is_actionable', models.BooleanField(default=False)),
                        ('is_urgent', models.BooleanField(default=False)),
                        ('is_edited', models.BooleanField(default=False)),
                        ('is_deleted', models.BooleanField(default=False)),
                        ('sent_at', models.DateTimeField(auto_now_add=True)),
                        ('synced_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                        ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.chatthread')),
                    ],
                    options={
                        'db_table': 'school_messageaudit',
                        'ordering': ['sent_at'],
                    },
                ),
                migrations.CreateModel(
                    name='Notification',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=100)),
                        ('message', models.TextField()),
                        ('is_read', models.BooleanField(default=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                        ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'school_notification',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='ChatActionResponse',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('response_type', models.CharField(max_length=50)),
                        ('responded_at', models.DateTimeField(auto_now_add=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_actions', to=settings.AUTH_USER_MODEL)),
                        ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='messaging.messageaudit')),
                    ],
                    options={
                        'db_table': 'school_chatactionresponse',
                        'unique_together': {('message', 'user')},
                    },
                ),
                migrations.CreateModel(
                    name='ThreadParticipant',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('last_read_timestamp', models.DateTimeField(blank=True, null=True)),
                        ('joined_at', models.DateTimeField(auto_now_add=True)),
                        ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='messaging.chatthread')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'school_threadparticipant',
                        'unique_together': {('thread', 'user')},
                    },
                ),
            ],
        ),
    ]
