# Generated by Django 6.0.1 on 2026-08-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_permission_adminextra_admininvitecode_and_more'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='chatthread',
                    name='related_student',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_threads', to='identity.studentextra'),
                ),
            ],
            database_operations=[]
        )
    ]
