# Generated by Django 6.0.7 on 2026-09-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_notice_deleted_at_notice_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatactionresponse',
            name='response_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='thread_type',
            field=models.CharField(choices=[('Direct', '1-on-1 Direct Message'), ('Broadcast', 'One-way Broadcast (Admin to Many)'), ('Group', 'Group Chat')], db_index=True, default='Direct', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(db_index=True, default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='audience',
            field=models.CharField(choices=[('All', 'All'), ('Teachers', 'Teachers Only'), ('Parents', 'Parents Only'), ('Students', 'Students Only')], db_index=True, default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
