# Generated by Django 6.0.1 on 2026-09-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('account_type', models.CharField(choices=[('bank', 'Bank Account'), ('petty_cash', 'Petty Cash'), ('mobile_money', 'Mobile Money')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'finance_cashaccount',
            },
        ),
        migrations.CreateModel(
            name='DocumentSequenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'finance_documentsequencecounter',
                'unique_together': {('document_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='DummyImmutableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('note', models.CharField(default='', max_length=50)),
            ],
            options={
                'app_label': 'finance',
            },
        ),
    ]
