# Generated by Django 6.0.1 on 2026-10-05 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_academicyear_is_active_and_more'),
        ('finance', '0002_studentfeeadjustment_decided_at_and_more'),
        ('identity', '0009_alter_adminextra_mobile_alter_adminextra_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_rules', to='academics.academicyear')),
                ('class_stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discount_rules', to='academics.classstream')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discount_rules', to='academics.gradelevel')),
                ('students', models.ManyToManyField(blank=True, related_name='discount_rules', to='identity.studentextra')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_rules', to='academics.examterm')),
            ],
            options={
                'db_table': 'finance_discountrule',
            },
        ),
        migrations.AddField(
            model_name='studentfeeadjustment',
            name='discount_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='finance.discountrule'),
        ),
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('fixed', 'Fixed amount'), ('percentage', 'Percentage')], max_length=10)),
                ('value', models.IntegerField(help_text='KES amount for kind=fixed (>= 0); whole-number percent 0-100 for kind=percentage.')),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, help_text='Leave empty to apply to all fees.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discount_types', to='finance.feecategory')),
            ],
            options={
                'db_table': 'finance_discounttype',
            },
        ),
        migrations.AddField(
            model_name='discountrule',
            name='discount_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='finance.discounttype'),
        ),
        migrations.AddField(
            model_name='studentfeeadjustment',
            name='discount_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='finance.discounttype'),
        ),
        migrations.AddConstraint(
            model_name='studentfeeadjustment',
            constraint=models.UniqueConstraint(condition=models.Q(('discount_rule__isnull', False)), fields=('discount_rule', 'student'), name='uniq_discount_rule_per_student'),
        ),
    ]
