# Generated by Django 6.0.1 on 2026-10-05 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_discountrule_studentfeeadjustment_discount_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeeadjustment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='finance.invoice'),
        ),
    ]
