# Hand-written -- NOT autogenerated. Track B step 8: state-only relocation of
# AcademicYear, Curriculum, Department, ExamTerm, GradeLevel, Pathway,
# Subject, SubjectSelectionRule, Tier, TimeSlot, Track, PresetCombination,
# CurriculumPreset, ClassStream, SubjectCategoryLimit, SubjectExclusionRule,
# SubjectPool, SubjectCurriculumProfile into the `academics` app.
# database_operations is empty, so this issues zero SQL -- it only tells
# Django's migration state that these 18 models now belong to `academics`.
# The physical tables (pinned via Meta.db_table in apps/academics/models.py)
# never move, including the `school_presetcombination_subjects` and
# `school_subjectpool_subjects` M2M join tables (pinned via db_table= on the
# fields themselves). The exact CreateModel/AddField field reprs below were
# taken verbatim from `manage.py makemigrations academics --dry-run -v3` --
# Django's own autodetector, not hand-transcribed -- to guarantee zero drift
# against `makemigrations --check`. This is by far the largest single Track B
# relocation: 8 other apps' own migrations (allocations, assignments,
# attendance, exams, results, staff, students, timetable) already have real
# FK fields whose `to=` recorded state points at `school.<model>` for these
# same 18 models -- each of those apps gets its own paired `0002_alter_*`
# migration (also hand-written from the same dry-run) updating `to=` to
# `academics.<model>`, and school/migrations/0098_... deletes these 18
# models from `school`'s state. All are database_operations=[] no-ops.
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0097_move_exams_results_models_to_apps'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='AcademicYear',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('year', models.CharField(help_text='e.g., 2026', max_length=10, unique=True)),
                        ('is_active', models.BooleanField(default=True, help_text='Is this the current academic year?')),
                        ('is_archived', models.BooleanField(default=False)),
                    ],
                    options={
                        'db_table': 'school_academicyear',
                    },
                ),
                migrations.CreateModel(
                    name='Curriculum',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('code', models.CharField(help_text="e.g. 'CBC', '8-4-4'", max_length=10, unique=True)),
                        ('name', models.CharField(help_text="e.g. 'Competency Based Curriculum'", max_length=100)),
                        ('is_active_for_new_grades', models.BooleanField(default=True)),
                        ('is_archived', models.BooleanField(default=False)),
                    ],
                    options={
                        'db_table': 'school_curriculum',
                        'ordering': ['name'],
                    },
                ),
                migrations.CreateModel(
                    name='Department',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=50)),
                        ('code', models.CharField(blank=True, help_text="Optional short code, e.g. 'SCI'.", max_length=10, null=True)),
                        ('description', models.CharField(blank=True, max_length=255)),
                        ('is_active', models.BooleanField(default=True, help_text='Inactive departments stay on existing subjects but drop out of pickers for new ones.')),
                        ('curriculum', models.ForeignKey(help_text="Which curriculum this department belongs to — CBC and 8-4-4 group subjects differently, so departments aren't shared across them.", on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academics.curriculum')),
                    ],
                    options={
                        'db_table': 'school_department',
                        'ordering': ['curriculum', 'name'],
                        'unique_together': {('code', 'curriculum'), ('name', 'curriculum')},
                    },
                ),
                migrations.CreateModel(
                    name='ExamTerm',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(help_text='e.g., Term 1', max_length=50)),
                        ('start_date', models.DateField()),
                        ('end_date', models.DateField()),
                        ('is_active', models.BooleanField(default=False)),
                        ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear')),
                    ],
                    options={
                        'db_table': 'school_examterm',
                    },
                ),
                migrations.CreateModel(
                    name='GradeLevel',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=50, unique=True)),
                        ('numeric_order', models.IntegerField(help_text='Used for sorting (e.g., 6 for Grade 6)')),
                        ('curriculum_type', models.CharField(choices=[('CBC', 'Competency Based Curriculum (CBC)'), ('8-4-4', 'Standard 8-4-4 Curriculum')], default='CBC', max_length=10)),
                        ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academics.curriculum')),
                    ],
                    options={
                        'db_table': 'school_gradelevel',
                    },
                ),
                migrations.CreateModel(
                    name='Pathway',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100)),
                        ('description', models.CharField(blank=True, max_length=255)),
                        ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathways', to='academics.curriculum')),
                    ],
                    options={
                        'db_table': 'school_pathway',
                        'unique_together': {('curriculum', 'name')},
                    },
                ),
                migrations.CreateModel(
                    name='Subject',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('code', models.CharField(max_length=10, unique=True)),
                        ('name', models.CharField(max_length=100)),
                        ('is_core', models.BooleanField(default=True, help_text='Is this mandatory for all students?')),
                        ('display_order', models.PositiveIntegerField(default=0, help_text='Controls subject ordering in the Allocation Matrix and similar subject lists.')),
                        ('allows_multiclass', models.BooleanField(default=False, help_text='Bypass clash prevention for subjects like PE')),
                        ('allow_double_periods', models.BooleanField(default=True, help_text='Uncheck for subjects like P.E. or Religious education that should never form double blocks.')),
                        ('earliest_allowed_time', models.TimeField(blank=True, help_text='Set to 09:30:00 for P.E. to prevent scheduling during cold early morning blocks.', null=True)),
                        ('requires_synchronized_grade_blocking', models.BooleanField(default=False, help_text="Check True for technical or elective blocks that must run concurrently across the entire grade level. This is the single source of truth is_tech_subject() reads — set it here instead of relying on the subject's name or department, so a newly added subject never needs a code change to be routed through the shared-block / elective-splitting engine.")),
                        ('synchronized_blocking_min_grade', models.PositiveIntegerField(blank=True, help_text="Only treat this subject as a synchronized/shared block from this grade's numeric order upward (e.g. a subject offered from Grade 8 down shouldn't force shared-block scheduling in Grade 7). Leave blank to apply at every grade this subject is taught.", null=True)),
                        ('department', models.ForeignKey(blank=True, help_text='Leave blank for an uncategorized subject — set it from the Academics Hub.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academics.department')),
                    ],
                    options={
                        'db_table': 'school_subject',
                    },
                ),
                migrations.CreateModel(
                    name='SubjectSelectionRule',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('min_subjects', models.PositiveIntegerField(default=7, help_text='Minimum subjects a student must take')),
                        ('max_subjects', models.PositiveIntegerField(default=8, help_text='Maximum subjects a student can take')),
                        ('grade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selection_rule', to='academics.gradelevel')),
                    ],
                    options={
                        'db_table': 'school_subjectselectionrule',
                    },
                ),
                migrations.CreateModel(
                    name='Tier',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(help_text='e.g. Junior Secondary', max_length=100)),
                        ('code', models.CharField(help_text='e.g. JSS', max_length=10)),
                        ('display_order', models.PositiveIntegerField(default=0)),
                        ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='academics.curriculum')),
                    ],
                    options={
                        'db_table': 'school_tier',
                        'ordering': ['display_order', 'name'],
                        'unique_together': {('curriculum', 'code')},
                    },
                ),
                migrations.AddField(
                    model_name='gradelevel',
                    name='tier',
                    field=models.ForeignKey(blank=True, help_text="Only meaningful when the grade's curriculum has tiers configured.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academics.tier'),
                ),
                migrations.CreateModel(
                    name='TimeSlot',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=15)),
                        ('start_time', models.TimeField()),
                        ('end_time', models.TimeField()),
                        ('is_global', models.BooleanField(default=False)),
                        ('global_label', models.CharField(blank=True, help_text="e.g., 'Morning Prep', 'Lunch Break'", max_length=100, null=True)),
                        ('is_remedial', models.BooleanField(default=False)),
                    ],
                    options={
                        'db_table': 'school_timeslot',
                        'ordering': ['day', 'start_time'],
                        'unique_together': {('day', 'start_time', 'end_time')},
                    },
                ),
                migrations.CreateModel(
                    name='Track',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100)),
                        ('description', models.CharField(blank=True, max_length=255)),
                        ('display_order', models.PositiveIntegerField(default=0)),
                        ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='academics.pathway')),
                    ],
                    options={
                        'db_table': 'school_track',
                        'ordering': ['display_order', 'name'],
                        'unique_together': {('pathway', 'name')},
                    },
                ),
                migrations.CreateModel(
                    name='PresetCombination',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(blank=True, help_text="Optional display name (e.g. 'Pure Sciences Combo 1'). Auto-derived from the subjects if left blank.", max_length=150)),
                        ('code', models.CharField(blank=True, help_text='Optional official KNEC combination code/number, if published.', max_length=20)),
                        ('is_active', models.BooleanField(default=True, help_text='Uncheck to retire a combination (e.g. the school stopped offering it) without deleting historical student selections that reference it.')),
                        ('subjects', models.ManyToManyField(db_table='school_presetcombination_subjects', related_name='preset_combinations', to='academics.subject')),
                        ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_combinations', to='academics.track')),
                    ],
                    options={
                        'db_table': 'school_presetcombination',
                        'ordering': ['track', 'name'],
                    },
                ),
                migrations.CreateModel(
                    name='CurriculumPreset',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(help_text='e.g., Standard 8-4-4, CBC Junior Sec.', max_length=100, unique=True)),
                        ('min_subjects', models.PositiveIntegerField(default=7, help_text='Default minimum subjects for this preset.')),
                        ('max_subjects', models.PositiveIntegerField(default=8, help_text='Default maximum subjects for this preset.')),
                        ('display_order', models.PositiveIntegerField(default=0)),
                        ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='academics.curriculum')),
                        ('pathway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets', to='academics.pathway')),
                        ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets', to='academics.tier')),
                        ('track', models.ForeignKey(blank=True, help_text="Only set when the preset's pathway has Tracks configured (e.g. STEM's Pure Sciences).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets', to='academics.track')),
                    ],
                    options={
                        'db_table': 'school_curriculumpreset',
                        'ordering': ['display_order', 'name'],
                    },
                ),
                migrations.CreateModel(
                    name='ClassStream',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=50)),
                        ('capacity', models.PositiveIntegerField(default=40)),
                        ('is_virtual', models.BooleanField(default=False, help_text='True if this is a temporary block grouping for electives.')),
                        ('is_deleted', models.BooleanField(db_index=True, default=False)),
                        ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to='school.teacherextra')),
                        ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='academics.gradelevel')),
                    ],
                    options={
                        'db_table': 'school_classstream',
                        'unique_together': {('name', 'grade', 'is_deleted')},
                    },
                ),
                migrations.CreateModel(
                    name='SubjectCategoryLimit',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('max_subjects', models.PositiveIntegerField(default=1)),
                        ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_limits', to='academics.department')),
                        ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_limits', to='academics.gradelevel')),
                    ],
                    options={
                        'db_table': 'school_subjectcategorylimit',
                        'unique_together': {('grade', 'department')},
                    },
                ),
                migrations.CreateModel(
                    name='SubjectExclusionRule',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('rule_type', models.CharField(choices=[('EXCLUDES', 'Mutually Exclusive'), ('REQUIRES', 'Co-Requisite')], default='EXCLUDES', max_length=10)),
                        ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_rules', to='academics.gradelevel')),
                        ('subject_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_by_a', to='academics.subject')),
                        ('subject_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_by_b', to='academics.subject')),
                    ],
                    options={
                        'db_table': 'school_subjectexclusionrule',
                        'unique_together': {('grade', 'subject_a', 'subject_b')},
                    },
                ),
                migrations.CreateModel(
                    name='SubjectPool',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('pool_type', models.CharField(choices=[('CORE_COMPULSORY', 'Core Compulsory'), ('PATHWAY_CORE', 'Pathway Core'), ('GUIDED_ELECTIVE', 'Guided Elective')], max_length=20)),
                        ('min_subjects', models.PositiveIntegerField(default=1)),
                        ('max_subjects', models.PositiveIntegerField(default=1)),
                        ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='academics.curriculumpreset')),
                        ('subjects', models.ManyToManyField(blank=True, db_table='school_subjectpool_subjects', related_name='pools', to='academics.subject')),
                    ],
                    options={
                        'db_table': 'school_subjectpool',
                        'unique_together': {('preset', 'pool_type')},
                    },
                ),
                migrations.CreateModel(
                    name='SubjectCurriculumProfile',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('is_core', models.BooleanField(blank=True, help_text="Overrides Subject.is_core for this curriculum/tier. Leave blank to inherit the subject's default.", null=True)),
                        ('total_lessons', models.PositiveIntegerField(blank=True, help_text="Weekly lesson count for this subject under this curriculum/tier. Used both to seed a brand-new grade's SubjectQuota and, when set, as the authoritative figure 'Auto-Fill Subject Quotas' reads instead of its generic department-based defaults.", null=True)),
                        ('double_lessons_required', models.PositiveIntegerField(blank=True, help_text='Overrides the default double-period count that goes with total_lessons above. Leave blank to fall back to the generic default (0).', null=True)),
                        ('remedial_lessons_required', models.PositiveIntegerField(blank=True, help_text='Overrides the default remedial-slot count that goes with total_lessons above. Leave blank to fall back to the generic default (1).', null=True)),
                        ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_profiles', to='academics.curriculum')),
                        ('department', models.ForeignKey(blank=True, help_text="This subject's department under this curriculum specifically — CBC and 8-4-4 group subjects differently, so a subject taught under both needs a department per curriculum, not one flat Subject.department. Set on the tier=None (whole-curriculum) row; per-tier rows for the same subject+curriculum should carry the same value, not a tier-specific one. Leave blank to inherit Subject.department.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_profiles', to='academics.department')),
                        ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_profiles', to='academics.subject')),
                        ('tier', models.ForeignKey(blank=True, help_text='Leave blank to apply to the whole curriculum; set to scope to one tier only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_profiles', to='academics.tier')),
                    ],
                    options={
                        'db_table': 'school_subjectcurriculumprofile',
                        'unique_together': {('subject', 'curriculum', 'tier')},
                    },
                ),
            ],
        ),
    ]
