# Generated by Django 6.0.1 on 2026-08-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('identity', '0002_permission_adminextra_admininvitecode_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='classstream',
                    name='class_teacher',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to='identity.teacherextra'),
                ),
            ],
            database_operations=[]
        )
    ]
