# Hand-written (not generated by makemigrations -- migrations are run by the project owner,
# not this session; see Hard Rule #1 in .claude/skills/sms-orient/SKILL.md). Verify against
# `python manage.py makemigrations academics --check --dry-run` before applying.
#
# Step 1 of 2 in the CurriculumPreset multi-tenant scoping rollout (see
# /home/jordan/.claude/plans/floofy-churning-mango.md). `school` starts nullable here so
# existing rows can be backfilled by `backfill_curriculum_preset_school` before migration
# 0005 makes it required.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_examterm_results_finalized_and_more'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumpreset',
            name='school',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                related_name='curriculum_presets', to='identity.school',
                help_text='Server-derived, never client-supplied — see get_current_school_id().',
            ),
        ),
        migrations.AlterField(
            model_name='curriculumpreset',
            name='name',
            field=models.CharField(max_length=100, help_text='e.g., Standard 8-4-4, CBC Junior Sec.'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumpreset',
            unique_together={('school', 'name')},
        ),
        migrations.AddIndex(
            model_name='curriculumpreset',
            index=models.Index(fields=['school', 'display_order'], name='curr_preset_school_order_idx'),
        ),
    ]
