# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_classstream_deleted_at_classstream_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathway',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
