# Generated by Django 6.0.7 on 2026-09-04 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_pathway_description_alter_track_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Is this the current academic year?'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='is_active_for_new_grades',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Inactive departments stay on existing subjects but drop out of pickers for new ones.'),
        ),
        migrations.AlterField(
            model_name='examterm',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='curriculum_type',
            field=models.CharField(choices=[('CBC', 'Competency Based Curriculum (CBC)'), ('8-4-4', 'Standard 8-4-4 Curriculum')], db_index=True, default='CBC', max_length=10),
        ),
        migrations.AlterField(
            model_name='subjectpool',
            name='pool_type',
            field=models.CharField(choices=[('CORE_COMPULSORY', 'Core Compulsory'), ('PATHWAY_CORE', 'Pathway Core'), ('GUIDED_ELECTIVE', 'Guided Elective')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['department', 'is_core'], name='subject_dept_core_idx'),
        ),
    ]
