# Generated by Django 6.0.1 on 2026-02-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_adminextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='parent_mobile',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='parent_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='mobile',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
