# Generated by Django 6.0.1 on 2026-02-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_studentextra_parent_mobile_studentextra_parent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
