# Generated by Django 6.0.1 on 2026-02-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_studentextra_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='cl',
            field=models.CharField(choices=[('Grade 7A', 'Grade 7A'), ('Grade 7B', 'Grade 7B'), ('Grade 8A', 'Grade 8A'), ('Grade 8B', 'Grade 8B'), ('Grade 9A', 'Grade 9A'), ('Grade 9B', 'Grade 9B'), ('Grade 10A', 'Grade 10A'), ('Grade 10B', 'Grade 10B'), ('Grade 11A', 'Grade 11A'), ('Grade 11B', 'Grade 11B'), ('Grade 12A', 'Grade 12A'), ('Grade 12B', 'Grade 12B')], default='Grade 7A', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='roll',
            field=models.CharField(max_length=20),
        ),
    ]
