# Generated by Django 6.0.1 on 2026-02-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_alter_studentextra_cl_alter_studentextra_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentextra',
            name='student',
        ),
        migrations.AddField(
            model_name='parentextra',
            name='students',
            field=models.ManyToManyField(to='school.studentextra'),
        ),
    ]
