# Generated by Django 6.0.1 on 2026-02-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_remove_parentextra_student_parentextra_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentextra',
            name='relationship',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian'), ('Other', 'Other')], default='Father', max_length=20),
        ),
    ]
