# Generated by Django 6.0.1 on 2026-02-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_parentextra_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherextra',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacherextra',
            name='id_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacherextra',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/Teacher/'),
        ),
        migrations.AlterField(
            model_name='teacherextra',
            name='salary',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
