# Generated by Django 6.0.1 on 2026-02-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_teacherextra_address_teacherextra_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/Student/'),
        ),
    ]
