# Generated by Django 6.0.1 on 2026-03-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_studentextra_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherextra',
            name='subjects',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
