# Generated by Django 6.0.1 on 2026-03-09 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_teacherextra_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('numeric_order', models.IntegerField(help_text='Used for sorting (e.g., 6 for Grade 6)')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Languages', 'Languages'), ('Mathematics', 'Mathematics'), ('Sciences', 'Sciences'), ('Humanities', 'Humanities'), ('Technical', 'Technical')], default='Languages', max_length=50)),
                ('is_core', models.BooleanField(default=True, help_text='Is this mandatory for all students?')),
            ],
        ),
        migrations.CreateModel(
            name='ClassStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=40)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='school.gradelevel')),
            ],
            options={
                'unique_together': {('name', 'grade')},
            },
        ),
    ]
