# Generated by Django 6.0.1 on 2026-03-09 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_alter_studentextra_cl'),
    ]

    operations = [
        migrations.AddField(
            model_name='classstream',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to='school.teacherextra'),
        ),
    ]
