# Generated by Django 6.0.1 on 2026-03-11 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_timetable_timeslot_subjectquota_lessonallocation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonallocation',
            unique_together={('timetable', 'time_slot', 'class_stream', 'subject'), ('timetable', 'time_slot', 'teacher')},
        ),
    ]
