# Generated by Django 6.0.1 on 2026-03-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_alter_lessonallocation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectquota',
            name='remedial_lessons_required',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_remedial',
            field=models.BooleanField(default=False),
        ),
    ]
