# Generated by Django 6.0.1 on 2026-03-20 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_subjectquota_remedial_lessons_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Excused', 'Excused')], default='Present', max_length=10)),
                ('remarks', models.CharField(blank=True, help_text="e.g., 'Sick leave', 'Arrived at 9 AM'", max_length=255, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='school.studentextra')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='school.classstream')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('class_stream', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('event_type', models.CharField(default='General', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.AddField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notices/'),
        ),
        migrations.AddField(
            model_name='notice',
            name='audience',
            field=models.CharField(choices=[('All', 'All'), ('Teachers', 'Teachers Only'), ('Parents', 'Parents Only'), ('Students', 'Students Only')], default='All', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(default='General Notice', max_length=200),
        ),
        migrations.AlterField(
            model_name='notice',
            name='by',
            field=models.CharField(default='School Admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='message',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='school.attendancesession'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('session', 'student')},
        ),
    ]
