# Generated by Django 6.0.1 on 2026-03-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_attendancerecord_attendancesession_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
