# Generated by Django 6.0.1 on 2026-03-24 08:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_notice_is_urgent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='e.g., 2026', max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this the current academic year?')),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GradingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.CharField(choices=[('CBC', 'Competency Based Curriculum (CBC)'), ('8-4-4', 'Standard 8-4-4 Curriculum')], default='8-4-4', max_length=10)),
                ('grade_label', models.CharField(help_text="e.g., 'A' or 'EE'", max_length=5)),
                ('min_score', models.DecimalField(decimal_places=2, help_text='Minimum percentage/score', max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, help_text='Maximum percentage/score', max_digits=5)),
                ('remarks', models.CharField(blank=True, help_text="e.g., 'Excellent', 'Exceeding Expectation'", max_length=100)),
            ],
            options={
                'ordering': ['-min_score'],
            },
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='curriculum_type',
            field=models.CharField(choices=[('CBC', 'Competency Based Curriculum (CBC)'), ('8-4-4', 'Standard 8-4-4 Curriculum')], default='CBC', max_length=10),
        ),
        migrations.CreateModel(
            name='ExamTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Term 1', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='school.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='ExamEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Term 1 CAT 1', max_length=100)),
                ('exam_type', models.CharField(choices=[('CAT', 'Continuous Assessment Test'), ('MAIN', 'Main/End of Term Exam')], default='CAT', max_length=10)),
                ('total_marks', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft - Teachers entering marks'), ('Submitted', 'Submitted - Waiting Admin Approval'), ('Published', 'Published - Visible to Students/Parents')], default='Draft', max_length=20)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='school.examterm')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('teacher_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='school.examevent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='school.studentextra')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
            ],
            options={
                'unique_together': {('exam', 'student', 'subject')},
            },
        ),
    ]
