# Generated by Django 6.0.1 on 2026-03-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_academicyear_gradingrule_gradelevel_curriculum_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examterm',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
