# Generated by Django 6.0.1 on 2026-03-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_examterm_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='examevent',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the exam was published.', null=True),
        ),
    ]
