# Generated by Django 6.0.1 on 2026-03-31 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_examevent_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.teacherextra'),
        ),
        migrations.CreateModel(
            name='StudentReportSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_teacher_remark', models.TextField(blank=True, help_text='Manual remark from the class teacher', null=True)),
                ('principal_remark', models.TextField(blank=True, help_text='Manual remark from the principal', null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_summaries', to='school.examevent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_summaries', to='school.studentextra')),
            ],
            options={
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
