# Generated by Django 6.0.1 on 2026-04-05 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_examresult_teacher_studentreportsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPerformanceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students_assessed', models.PositiveIntegerField(default=0)),
                ('stream_mean_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stream_mean_grade', models.CharField(blank=True, max_length=5, null=True)),
                ('deviation_from_last_term', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('class_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classstream')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.examterm')),
            ],
            options={
                'unique_together': {('term', 'class_stream')},
            },
        ),
        migrations.CreateModel(
            name='StudentTermResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mean_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mean_grade', models.CharField(blank=True, max_length=5, null=True)),
                ('stream_position', models.PositiveIntegerField(blank=True, null=True)),
                ('class_position', models.PositiveIntegerField(blank=True, null=True)),
                ('class_teacher_remark', models.TextField(blank=True, null=True)),
                ('principal_remark', models.TextField(blank=True, null=True)),
                ('days_present', models.PositiveIntegerField(default=0, help_text='Total days attended this term')),
                ('days_absent', models.PositiveIntegerField(default=0, help_text='Total days missed this term')),
                ('results_withheld', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('class_stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.classstream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_results', to='school.studentextra')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.examterm')),
            ],
            options={
                'unique_together': {('student', 'term')},
            },
        ),
        migrations.CreateModel(
            name='SubjectTermResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('subject_teacher_remark', models.CharField(blank=True, max_length=150, null=True)),
                ('cbc_rubric_data', models.JSONField(blank=True, help_text='Stores CBC competency rubrics', null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='school.studentextra')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.examterm')),
            ],
            options={
                'unique_together': {('student', 'subject', 'term')},
            },
        ),
    ]
