# Generated by Django 6.0.1 on 2026-04-08 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0035_classperformanceanalytics_studenttermresult_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassExamStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft - Teachers entering marks'), ('Submitted', 'Submitted - Waiting Admin Approval'), ('Published', 'Published - Visible to Students/Parents')], default='Draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('class_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_publish_statuses', to='school.classstream')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_publish_statuses', to='school.examevent')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('exam', 'class_stream')},
            },
        ),
    ]
