# Generated by Django 6.0.1 on 2026-04-22 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_classexamstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='elective_subjects',
            field=models.ManyToManyField(blank=True, related_name='students_enrolled', to='school.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='allows_multiclass',
            field=models.BooleanField(default=False, help_text='Bypass clash prevention for subjects like PE'),
        ),
        migrations.CreateModel(
            name='SubjectBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., G10-Humanities-Block', max_length=100)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_blocks', to='school.gradelevel')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='school.subjectblock'),
        ),
        migrations.CreateModel(
            name='SubjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='school.classstream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_allocations', to='school.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='school.teacherextra')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.examterm')),
            ],
            options={
                'unique_together': {('classroom', 'subject', 'academic_year', 'term')},
            },
        ),
    ]
