# Generated by Django 6.0.1 on 2026-05-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0037_studentextra_elective_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='roll',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
