# Generated by Django 6.0.1 on 2026-05-07 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0038_alter_studentextra_roll'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thread_type', models.CharField(choices=[('Direct', '1-on-1 Direct Message'), ('Broadcast', 'One-way Broadcast (Admin to Many)'), ('Group', 'Group Chat')], default='Direct', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_threads', to='school.studentextra')),
            ],
        ),
        migrations.CreateModel(
            name='ChatUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_hours_start', models.TimeField(blank=True, null=True)),
                ('working_hours_end', models.TimeField(blank=True, null=True)),
                ('auto_reply_enabled', models.BooleanField(default=True)),
                ('auto_reply_message', models.CharField(default='I am currently offline. I will respond during standard school working hours.', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumStrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Numbers', 'Measurement'", max_length=255)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strands', to='school.subject')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumSubStrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Fractions', 'Time'", max_length=255)),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_strands', to='school.curriculumstrand')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('assignment_type', models.CharField(choices=[('Holiday', 'Holiday Assignment'), ('In-Term', 'In-Term / Weekend Project')], default='Holiday', max_length=20)),
                ('curriculum_type', models.CharField(default='CBC', max_length=10)),
                ('publish_date', models.DateTimeField(help_text='When students can first see and open this.')),
                ('due_date', models.DateTimeField(help_text='The official deadline. Submissions after this are marked LATE.')),
                ('cutoff_date', models.DateTimeField(help_text='The absolute lockout. No submissions accepted after this minute.')),
                ('is_quiz', models.BooleanField(default=False, help_text='If True, turns this into a strictly timed assessment.')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Time limit in minutes (e.g., 45)', null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft - Hidden from students'), ('Published', 'Published - Visible and Active'), ('Closed', 'Closed - Past due date, no new submissions')], default='Draft', max_length=20)),
                ('total_max_score', models.IntegerField(default=0, help_text='Auto-tallied from questions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='school.classstream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_created', to='school.teacherextra')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.examterm')),
                ('strand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.curriculumstrand')),
                ('sub_strand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.curriculumsubstrand')),
            ],
        ),
        migrations.CreateModel(
            name='MessageAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_message_id', models.CharField(max_length=100, unique=True)),
                ('message_body', models.TextField()),
                ('is_actionable', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='school.chatthread')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice - Auto Graded'), ('SHORT_ANSWER', 'Short Answer - Exact Match Auto Graded'), ('ESSAY', 'Essay/Long Text - Manual Grade'), ('FILE_UPLOAD', 'File/Image Upload - Manual Grade')], max_length=20)),
                ('is_auto_graded', models.BooleanField(default=False)),
                ('max_score', models.IntegerField(default=1)),
                ('exact_match_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='school.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='school.question')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, help_text='Crucial for calculating Quiz duration.', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('grading_status', models.CharField(choices=[('Pending', 'Pending - Auto-marked, waiting for manual review'), ('Graded', 'Fully Graded'), ('Returned', 'Returned for Revision')], default='Pending', max_length=20)),
                ('total_awarded_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overall_feedback', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='school.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='school.studentextra')),
            ],
            options={
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='assignment_submissions/')),
                ('awarded_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('teacher_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.questionoption')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='school.studentsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='ChatActionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(max_length=50)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_actions', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='school.messageaudit')),
            ],
            options={
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ThreadParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_timestamp', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='school.chatthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('thread', 'user')},
            },
        ),
    ]
