# Generated by Django 6.0.5 on 2026-05-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0039_chatthread_chatuserprofile_curriculumstrand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageaudit',
            name='attachment_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
