# Generated by Django 6.0.5 on 2026-05-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0040_messageaudit_attachment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='teacher_attachment',
            field=models.FileField(blank=True, help_text='Optional master PDF/Doc for the assignment', null=True, upload_to='assignments/teacher_files/'),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='student_attachment',
            field=models.FileField(blank=True, help_text='Optional PDF/Image uploaded by the student', null=True, upload_to='assignments/student_files/'),
        ),
    ]
