# Generated by Django 6.0.5 on 2026-05-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0041_assignment_teacher_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='selected_option',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='school.questionoption'),
        ),
    ]
