# Generated by Django 6.0.5 on 2026-05-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0042_remove_studentanswer_selected_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumsubstrand',
            name='strand',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='strand',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='sub_strand',
        ),
        migrations.AddField(
            model_name='assignment',
            name='strand_name',
            field=models.CharField(blank=True, help_text="e.g., 'Numbers', 'Measurement'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='required_answers',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Used for CHECKBOX questions', null=True),
        ),
        migrations.DeleteModel(
            name='CurriculumStrand',
        ),
        migrations.DeleteModel(
            name='CurriculumSubStrand',
        ),
    ]
