# Generated by Django 6.0.5 on 2026-05-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0043_remove_curriculumsubstrand_strand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubmission',
            name='grading_status',
            field=models.CharField(choices=[('Pending', 'Pending - Auto-marked, waiting for manual review'), ('Graded', 'Graded (Draft) - Hidden from student'), ('Published', 'Published - Grades Released to Student'), ('Returned', 'Returned for Revision')], default='Pending', max_length=20),
        ),
    ]
