# Generated by Django 6.0.5 on 2026-05-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0044_alter_studentsubmission_grading_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='cutoff_date',
            field=models.DateTimeField(blank=True, help_text='The absolute lockout. No submissions accepted after this minute.', null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='The official deadline. Submissions after this are marked LATE.', null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='publish_date',
            field=models.DateTimeField(blank=True, help_text='When students can first see and open this.', null=True),
        ),
    ]
