# Generated by Django 6.0.5 on 2026-05-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0045_alter_assignment_cutoff_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='teacher_returned_file',
            field=models.FileField(blank=True, help_text='Optional annotated file sent back to the student', null=True, upload_to='assignments/returned_files/'),
        ),
    ]
