# Generated by Django 6.0.5 on 2026-05-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0046_studentsubmission_teacher_returned_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='teacher_corrected_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
