# Generated by Django 6.0.1 on 2026-06-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0047_studentanswer_teacher_corrected_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='enrollment_notes',
            field=models.TextField(blank=True, help_text='Reason for suspension/expulsion/transfer', null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='enrollment_state',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Expelled', 'Expelled'), ('Transferred', 'Transferred Out')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='last_enrollment_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
