# Generated by Django 6.0.5 on 2026-06-15 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0048_studentextra_enrollment_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectSelectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_subjects', models.PositiveIntegerField(default=7, help_text='Minimum subjects a student must take')),
                ('max_subjects', models.PositiveIntegerField(default=8, help_text='Maximum subjects a student can take')),
                ('grade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selection_rule', to='school.gradelevel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending Admin Approval'), ('Approved', 'Approved & Locked'), ('Rejected', 'Rejected by Admin')], default='Pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='school.studentextra')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
            ],
            options={
                'unique_together': {('student', 'subject', 'academic_year')},
            },
        ),
    ]
