# Generated by Django 6.0.5 on 2026-06-16 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0049_subjectselectionrule_studentsubjectenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCategoryLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Languages', 'Languages'), ('Mathematics', 'Mathematics'), ('Sciences', 'Sciences'), ('Humanities', 'Humanities'), ('Technical', 'Technical')], max_length=50)),
                ('max_subjects', models.PositiveIntegerField(default=1)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_limits', to='school.gradelevel')),
            ],
            options={
                'unique_together': {('grade', 'department')},
            },
        ),
        migrations.CreateModel(
            name='SubjectExclusionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_rules', to='school.gradelevel')),
                ('subject_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_by_a', to='school.subject')),
                ('subject_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_by_b', to='school.subject')),
            ],
            options={
                'unique_together': {('grade', 'subject_a', 'subject_b')},
            },
        ),
    ]
