# Generated by Django 6.0.5 on 2026-06-18 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0050_subjectcategorylimit_subjectexclusionrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classstream',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='studentextra',
            name='elective_subjects',
        ),
        migrations.AddField(
            model_name='classstream',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='classstream',
            name='is_virtual',
            field=models.BooleanField(default=False, help_text='True if this is a temporary block grouping for electives.'),
        ),
        migrations.AlterUniqueTogether(
            name='classstream',
            unique_together={('name', 'grade', 'is_deleted')},
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Created Resource'), ('UPDATE', 'Modified Settings / Rules'), ('DELETE', 'Soft Deleted Resource'), ('RESTORE', 'Restored Soft Deleted Resource'), ('SIMULATION', 'Executed Allocation Simulation'), ('EXECUTION', 'Committed Live Allocation Splits')], max_length=20)),
                ('module', models.CharField(help_text="e.g., 'SplittingEngine', 'ClassStream'", max_length=100)),
                ('description', models.TextField(help_text='Detailed summary of the operational event.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SubjectSplittingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_class_size', models.PositiveIntegerField(default=45, help_text='Max students per teacher before a split.')),
                ('allocation_mode', models.CharField(choices=[('Split_Balance', 'Auto-Split & Balance Streams'), ('Co_Teaching', 'Co-Teaching (Single Massive Group)'), ('Strict_Cap', 'Strict Enrollment Cap')], default='Split_Balance', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splitting_rules', to='school.gradelevel')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splitting_rules', to='school.subject')),
            ],
            options={
                'unique_together': {('grade', 'subject')},
            },
        ),
    ]
