# Generated by Django 6.0.5 on 2026-06-18 21:38

import school.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0051_alter_classstream_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='teacher_attachment',
            field=models.FileField(blank=True, help_text='Optional master PDF/Doc for the assignment', null=True, upload_to='assignments/teacher_files/', validators=[school.validators.safe_document_validator]),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_submissions/', validators=[school.validators.safe_document_validator]),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='student_attachment',
            field=models.FileField(blank=True, help_text='Optional PDF/Image uploaded by the student', null=True, upload_to='assignments/student_files/', validators=[school.validators.safe_document_validator]),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='teacher_returned_file',
            field=models.FileField(blank=True, help_text='Optional annotated file sent back to the student', null=True, upload_to='assignments/returned_files/', validators=[school.validators.safe_document_validator]),
        ),
    ]
