# Generated by Django 6.0.5 on 2026-06-19 07:07

import school.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0052_alter_assignment_teacher_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notices/', validators=[school.validators.safe_document_validator]),
        ),
    ]
