# Generated by Django 6.0.5 on 2026-06-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0053_alter_notice_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='total_max_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Auto-tallied from questions', max_digits=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
