# Generated by Django 6.0.5 on 2026-06-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0054_alter_assignment_total_max_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Standard 8-4-4, CBC Junior Sec.', max_length=100, unique=True)),
                ('min_subjects', models.PositiveIntegerField(default=7, help_text='Default minimum subjects for this preset.')),
                ('max_subjects', models.PositiveIntegerField(default=8, help_text='Default maximum subjects for this preset.')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalAllocationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_subjects_per_class', models.PositiveIntegerField(default=2)),
                ('max_classes_per_subject', models.PositiveIntegerField(default=2)),
                ('allow_cross_grade_teaching', models.BooleanField(default=False)),
                ('enforcement_mode', models.CharField(choices=[('STRICT', 'Strict Hard Blocks (Prevent Saves)'), ('SOFT', 'Soft Enforcement (Allow Saves with Warnings)')], default='STRICT', max_length=10)),
            ],
        ),
    ]
