# Generated by Django 6.0.5 on 2026-06-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0055_curriculumpreset_globalallocationpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalallocationpolicy',
            name='max_total_class_groups',
            field=models.PositiveIntegerField(default=6, help_text='Max distinct physical/virtual groups a teacher can manage.'),
        ),
        migrations.AddField(
            model_name='globalallocationpolicy',
            name='max_weekly_lessons',
            field=models.PositiveIntegerField(default=28, help_text='Total teaching periods allowed per week.'),
        ),
    ]
