# Generated by Django 6.0.5 on 2026-06-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0056_globalallocationpolicy_max_total_class_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalallocationpolicy',
            name='enforce_prep_consolidation',
            field=models.BooleanField(default=True, help_text='If True, the auto-drafter will magnetically prioritize teachers sitting below the minimum stream count.'),
        ),
        migrations.AddField(
            model_name='globalallocationpolicy',
            name='min_classes_per_subject',
            field=models.PositiveIntegerField(default=2, help_text='Target minimum streams a teacher should handle for a subject to optimize prep time.'),
        ),
    ]
