# Generated by Django 6.0.5 on 2026-07-01 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0057_globalallocationpolicy_enforce_prep_consolidation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetablePedagogyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_consecutive_periods', models.PositiveIntegerField(default=3, help_text='Maximum lessons a teacher can handle back-to-back before a mandatory break.')),
                ('max_daily_subject_frequency', models.PositiveIntegerField(default=2, help_text="Maximum times a single subject can appear in a classroom's daily schedule (including doubles).")),
                ('min_subject_spacing_periods', models.PositiveIntegerField(default=2, help_text='Minimum period gap required between two single lessons of the same subject on the same day.')),
                ('allow_remedial_double_periods', models.BooleanField(default=False, help_text='If True, early morning or late evening remedial blocks can be linked as double periods.')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='allow_double_periods',
            field=models.BooleanField(default=True, help_text='Uncheck for subjects like P.E. or Religious education that should never form double blocks.'),
        ),
        migrations.AddField(
            model_name='subject',
            name='earliest_allowed_time',
            field=models.TimeField(blank=True, help_text='Set to 09:30:00 for P.E. to prevent scheduling during cold early morning blocks.', null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='requires_synchronized_grade_blocking',
            field=models.BooleanField(default=False, help_text='Check True for technical or elective blocks that must run concurrently across the entire grade level.'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school.academicyear'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school.examterm'),
        ),
    ]
