# Generated by Django 6.0.5 on 2026-07-04 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0058_timetablepedagogypolicy_subject_allow_double_periods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectblock',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_blocks', to='school.academicyear'),
        ),
        migrations.AddField(
            model_name='subjectblock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectblock',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_blocks', to='school.examterm'),
        ),
        migrations.AddField(
            model_name='subjectblock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='timetablepedagogypolicy',
            name='heavy_day_threshold',
            field=models.PositiveIntegerField(default=5, help_text="The number of lessons that defines a 'Heavy Workload Day' for a teacher."),
        ),
        migrations.AddField(
            model_name='timetablepedagogypolicy',
            name='prevent_consecutive_heavy_days',
            field=models.BooleanField(default=True, help_text="If True, the auto-generator will heavily penalize giving a teacher two 'Heavy Days' in a row."),
        ),
        migrations.AlterField(
            model_name='subjectblock',
            name='name',
            field=models.CharField(help_text='e.g., G10-Humanities-Block or Form 3 Technical Electives', max_length=100),
        ),
        migrations.AlterField(
            model_name='timetablepedagogypolicy',
            name='max_daily_subject_frequency',
            field=models.PositiveIntegerField(default=2, help_text="Maximum times a single subject can appear in a classroom's daily schedule."),
        ),
        migrations.AlterUniqueTogether(
            name='subjectblock',
            unique_together={('name', 'grade_level', 'academic_year', 'term')},
        ),
        migrations.CreateModel(
            name='DailyCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The specific calendar day the cover is needed.')),
                ('notes', models.TextField(blank=True, help_text="e.g., 'Sick leave', 'Attending seminar'", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('absent_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='school.teacherextra')),
                ('covering_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers_provided', to='school.teacherextra')),
                ('target_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='school.lessonallocation')),
            ],
            options={
                'unique_together': {('date', 'target_lesson')},
            },
        ),
        migrations.CreateModel(
            name='TeacherStructuralAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, help_text="e.g., 'HOD Meeting', 'Part-time off-day'", max_length=100, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_slots', to='school.teacherextra')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.timeslot')),
            ],
            options={
                'unique_together': {('teacher', 'time_slot')},
            },
        ),
    ]
