# Generated by Django 6.0.5 on 2026-07-09 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0059_subjectblock_academic_year_subjectblock_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Casual', 'Casual Leave'), ('Sick', 'Medical/Sick Leave'), ('Maternity', 'Maternity/Paternity Leave'), ('Seminar', 'Official Duty / Seminar'), ('Compassionate', 'Compassionate Leave')], max_length=20)),
                ('start_date', models.DateField(help_text='First day of leave.')),
                ('end_date', models.DateField(help_text='Last day of leave (inclusive).')),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=15)),
                ('reason', models.TextField(blank=True, help_text='Optional context notes.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='school.teacherextra')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LongTermReliefAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('absent_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relief_covers_needed', to='school.teacherextra')),
                ('relief_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relief_covers_provided', to='school.teacherextra')),
                ('associated_leave', models.OneToOneField(help_text='Links directly to an approved long-term leave instance.', limit_choices_to={'status': 'Approved'}, on_delete=django.db.models.deletion.CASCADE, to='school.teacherleave')),
            ],
            options={
                'unique_together': {('absent_teacher', 'start_date', 'end_date')},
            },
        ),
    ]
