# Generated by Django 6.0.5 on 2026-07-10 11:04

from django.db import migrations, models


def backfill_subjects_m2m(apps, schema_editor):
    """
    Copies the old global Subject.subject_block FK onto the new grade/term-scoped
    SubjectBlock.subjects M2M, so existing block memberships survive the move.
    Uses a direct insert into the auto-created through table rather than the ORM
    M2M manager, since the manager proved unreliable here for a field added
    earlier in this same migration.
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "INSERT INTO school_subjectblock_subjects (subjectblock_id, subject_id) "
            "SELECT subject_block_id, id FROM school_subject WHERE subject_block_id IS NOT NULL"
        )


def noop_reverse(apps, schema_editor):
    # Deliberately not reversible: once a subject legitimately sits in more than
    # one block (the whole point of this migration), there's no well-defined way
    # to collapse M2M membership back into a single FK value.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0060_teacherleave_longtermreliefassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectblock',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='blocks', to='school.subject'),
        ),
        migrations.RunPython(backfill_subjects_m2m, noop_reverse),
    ]
