# Generated by Django 6.0.5 on 2026-07-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0061_subjectblock_subjects_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_block',
        ),
    ]
