# Generated by Django 6.0.5 on 2026-07-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0063_studenttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectblock',
            name='period_structure',
            field=models.CharField(choices=[('ALL_DOUBLE', 'All Double Periods'), ('ALL_SINGLE', 'All Single Periods'), ('MIXED', 'Mixed (Each Subject Uses Its Own Quota Split)')], default='MIXED', help_text="Governs how the quota/timetable engines split this block's lessons between single and double periods — e.g. Technical option blocks are usually ALL_DOUBLE (practical sessions), while a Humanities block is usually ALL_SINGLE.", max_length=10),
        ),
    ]
