# Generated by Django 6.0.5 on 2026-07-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0064_subjectblock_period_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherextra',
            name='qualified_subjects',
            field=models.ManyToManyField(blank=True, related_name='qualified_teachers', to='school.subject'),
        ),
    ]
