# Generated by Django 6.0.5 on 2026-07-12 05:39

import django.db.models.deletion
import school.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0066_permission_role_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='additional_class_streams',
            field=models.ManyToManyField(blank=True, help_text='Extra class streams (beyond the primary class_stream) that also receive this assignment.', related_name='shared_assignments', to='school.classstream'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='allow_resubmission',
            field=models.BooleanField(default=False, help_text='If True, students may resubmit after their first submission.'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, help_text='If set, only these students are assigned this work. If empty, the whole class_stream (and additional_class_streams) is targeted.', related_name='specific_assignments', to='school.studentextra'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_group_assignment',
            field=models.BooleanField(default=False, help_text="If True, one member's submission is shared across the whole group."),
        ),
        migrations.AddField(
            model_name='assignment',
            name='late_penalty_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Flat percentage deducted from the awarded score when a submission is late.', max_digits=5),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of submit attempts allowed per student.'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='reference_links',
            field=models.JSONField(blank=True, default=list, help_text='List of {label, url} reference links for students.'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='reference_notes',
            field=models.TextField(blank=True, help_text='Free-text reference material / instructions.', null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1, help_text='Which submit attempt this is, for max_attempts enforcement.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice - Auto Graded'), ('CHECKBOX', 'Checkbox - Multi-Select Auto Graded'), ('SHORT_ANSWER', 'Short Answer - Exact Match Auto Graded'), ('ESSAY', 'Essay/Long Text - Manual Grade'), ('FILE_UPLOAD', 'File/Image Upload - Manual Grade')], max_length=20),
        ),
        migrations.CreateModel(
            name='AssignmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignments/teacher_files/extra/', validators=[school.validators.safe_document_validator])),
                ('label', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='school.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='school.assignment')),
                ('members', models.ManyToManyField(blank=True, related_name='assignment_groups', to='school.studentextra')),
            ],
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_text', models.CharField(max_length=255)),
                ('max_points', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_criteria', to='school.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='school.studentanswer')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='school.rubriccriterion')),
            ],
            options={
                'unique_together': {('answer', 'criterion')},
            },
        ),
    ]
