# Generated by Django 6.0.5 on 2026-07-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0067_assignment_additional_class_streams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_system_role',
            field=models.BooleanField(default=False),
        ),
    ]
