# Generated by Django 6.0.5 on 2026-07-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0068_role_is_system_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="e.g. 'CBC', '8-4-4'", max_length=10, unique=True)),
                ('name', models.CharField(help_text="e.g. 'Competency Based Curriculum'", max_length=100)),
                ('is_active_for_new_grades', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='curriculumpreset',
            name='tier',
            field=models.CharField(blank=True, choices=[('JSS', 'Junior Secondary'), ('SSS', 'Senior Secondary')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='tier',
            field=models.CharField(blank=True, choices=[('JSS', 'Junior Secondary'), ('SSS', 'Senior Secondary')], help_text='Only meaningful when curriculum is CBC.', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='subjectexclusionrule',
            name='rule_type',
            field=models.CharField(choices=[('EXCLUDES', 'Mutually Exclusive'), ('REQUIRES', 'Co-Requisite')], default='EXCLUDES', max_length=10),
        ),
        migrations.AddField(
            model_name='curriculumpreset',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='school.curriculum'),
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='school.curriculum'),
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathways', to='school.curriculum')),
            ],
            options={
                'unique_together': {('curriculum', 'name')},
            },
        ),
        migrations.AddField(
            model_name='curriculumpreset',
            name='pathway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets', to='school.pathway'),
        ),
        migrations.CreateModel(
            name='SubjectPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_type', models.CharField(choices=[('CORE_COMPULSORY', 'Core Compulsory'), ('PATHWAY_CORE', 'Pathway Core'), ('GUIDED_ELECTIVE', 'Guided Elective')], max_length=20)),
                ('min_subjects', models.PositiveIntegerField(default=1)),
                ('max_subjects', models.PositiveIntegerField(default=1)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='school.curriculumpreset')),
                ('subjects', models.ManyToManyField(blank=True, related_name='pools', to='school.subject')),
            ],
            options={
                'unique_together': {('preset', 'pool_type')},
            },
        ),
    ]
