# Generated by Django 6.0.7 on 2026-07-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0069_curriculum_curriculumpreset_tier_gradelevel_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminextra',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
