# Generated by Django 6.0.1 on 2026-07-15 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0070_adminextra_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPathwaySelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved & Locked'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='school.pathway')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_selections', to='school.studentextra')),
            ],
            options={
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
