# Generated by Django 6.0.7 on 2026-07-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0071_studentpathwayselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminextra',
            name='code_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminextra',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
