# Generated by Django 6.0.1 on 2026-07-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0072_adminextra_code_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalallocationpolicy',
            name='timetable_capacity_buffer_percent',
            field=models.PositiveIntegerField(default=10, help_text="Safety margin subtracted from a teacher's real free-slot count (total time slots minus their structural blackouts) before the allocation engine will assign them more lessons. Fatigue rules (consecutive-period caps, heavy-day thresholds, subject spacing) aren't modeled here, so this buffer accounts for the usable capacity they eat into that a raw slot count alone wouldn't show."),
        ),
    ]
