# Generated by Django 6.0.7 on 2026-07-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0073_globalallocationpolicy_timetable_capacity_buffer_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageaudit',
            name='firebase_message_id',
        ),
        migrations.AddField(
            model_name='messageaudit',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messageaudit',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messageaudit',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messageaudit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='messageaudit',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
