# Generated by Django 6.0.7 on 2026-07-17 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0074_remove_messageaudit_firebase_message_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Junior Secondary', max_length=100)),
                ('code', models.CharField(help_text='e.g. JSS', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='school.curriculum')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('curriculum', 'code')},
            },
        ),
        migrations.AlterField(
            model_name='curriculumpreset',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets', to='school.tier'),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='tier',
            field=models.ForeignKey(blank=True, help_text="Only meaningful when the grade's curriculum has tiers configured.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='school.tier'),
        ),
    ]
