# Generated by Django 6.0.1 on 2026-07-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0075_tier_alter_curriculumpreset_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls subject ordering in the Allocation Matrix and similar subject lists.'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.CharField(choices=[('Languages', 'Languages'), ('Mathematics', 'Mathematics'), ('Sciences', 'Sciences'), ('Humanities', 'Humanities'), ('Technical', 'Technical'), ('PE', 'Physical Education')], default='Languages', max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectcategorylimit',
            name='department',
            field=models.CharField(choices=[('Languages', 'Languages'), ('Mathematics', 'Mathematics'), ('Sciences', 'Sciences'), ('Humanities', 'Humanities'), ('Technical', 'Technical'), ('PE', 'Physical Education')], max_length=50),
        ),
    ]
