# Generated by Django 6.0.1 on 2026-07-18 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0077_staffextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffextra',
            name='requested_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_applicants', to='school.role'),
        ),
    ]
