# Generated by Django 6.0.7 on 2026-07-21 07:38

import django.db.models.deletion
import school.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0078_staffextra_requested_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffextra',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/Staff/', validators=[school.validators.profile_pic_validator]),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/Student/', validators=[school.validators.profile_pic_validator]),
        ),
        migrations.AlterField(
            model_name='systemauditlog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Created Resource'), ('UPDATE', 'Modified Settings / Rules'), ('DELETE', 'Soft Deleted Resource'), ('RESTORE', 'Restored Soft Deleted Resource'), ('SIMULATION', 'Executed Allocation Simulation'), ('EXECUTION', 'Committed Live Allocation Splits'), ('APPROVE', 'Approved Pending Account'), ('REJECT', 'Rejected Pending Account'), ('AUTH_SUCCESS', 'Authentication Succeeded'), ('AUTH_FAILURE', 'Authentication Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherextra',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/Teacher/', validators=[school.validators.profile_pic_validator]),
        ),
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Completed'), ('FAILURE', 'Failed')], default='PENDING', max_length=10)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
