# Generated by Django 6.0.1 on 2026-07-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0079_systemauditlog_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='family_structure',
            field=models.CharField(blank=True, choices=[('both', 'Both Parents'), ('single', 'Single Parent'), ('guardian', 'Guardian')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='father_mobile',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='guardian_mobile',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='guardian_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='mother_mobile',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='single_parent_type',
            field=models.CharField(blank=True, choices=[('Mother', 'Mother'), ('Father', 'Father')], max_length=10, null=True),
        ),
    ]
