# Generated by Django 6.0.7 on 2026-07-22 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0083_backfill_qualified_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='school.pathway')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('pathway', 'name')},
            },
        ),
        migrations.AddField(
            model_name='curriculumpreset',
            name='track',
            field=models.ForeignKey(blank=True, help_text="Only set when the preset's pathway has Tracks configured (e.g. STEM's Pure Sciences).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets', to='school.track'),
        ),
        migrations.AddField(
            model_name='studentpathwayselection',
            name='track',
            field=models.ForeignKey(blank=True, help_text='Required whenever the chosen Pathway has Tracks configured — see api_student_pathway_request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_selections', to='school.track'),
        ),
    ]
