# Generated by Django 6.0.1 on 2026-07-27 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0084_track_curriculumpreset_track_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCurriculumProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_core', models.BooleanField(blank=True, help_text="Overrides Subject.is_core for this curriculum/tier. Leave blank to inherit the subject's default.", null=True)),
                ('total_lessons', models.PositiveIntegerField(blank=True, help_text="Overrides the factory-default weekly lesson count (4) used when auto-seeding this grade's SubjectQuota.", null=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_profiles', to='school.curriculum')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_profiles', to='school.subject')),
                ('tier', models.ForeignKey(blank=True, help_text='Leave blank to apply to the whole curriculum; set to scope to one tier only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_profiles', to='school.tier')),
            ],
            options={
                'unique_together': {('subject', 'curriculum', 'tier')},
            },
        ),
    ]
