# Generated by Django 6.0.1 on 2026-07-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0085_subjectcurriculumprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonallocation',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timetablepedagogypolicy',
            name='enforcement_mode',
            field=models.CharField(choices=[('STRICT', 'Strict Hard Blocks (Prevent Saves)'), ('SOFT', 'Soft Enforcement (Allow Saves with Warnings)')], default='STRICT', max_length=10),
        ),
    ]
