# Generated by Django 6.0.1 on 2026-07-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0086_lessonallocation_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectcurriculumprofile',
            name='double_lessons_required',
            field=models.PositiveIntegerField(blank=True, help_text='Overrides the default double-period count that goes with total_lessons above. Leave blank to fall back to the generic default (0).', null=True),
        ),
        migrations.AddField(
            model_name='subjectcurriculumprofile',
            name='remedial_lessons_required',
            field=models.PositiveIntegerField(blank=True, help_text='Overrides the default remedial-slot count that goes with total_lessons above. Leave blank to fall back to the generic default (1).', null=True),
        ),
        migrations.AlterField(
            model_name='subjectcurriculumprofile',
            name='total_lessons',
            field=models.PositiveIntegerField(blank=True, help_text="Weekly lesson count for this subject under this curriculum/tier. Used both to seed a brand-new grade's SubjectQuota and, when set, as the authoritative figure 'Auto-Fill Subject Quotas' reads instead of its generic department-based defaults.", null=True),
        ),
    ]
