# Generated by Django 6.0.1 on 2026-07-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0087_subjectcurriculumprofile_double_lessons_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='synchronized_blocking_min_grade',
            field=models.PositiveIntegerField(blank=True, help_text="Only treat this subject as a synchronized/shared block from this grade's numeric order upward (e.g. a subject offered from Grade 8 down shouldn't force shared-block scheduling in Grade 7). Leave blank to apply at every grade this subject is taught.", null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='requires_synchronized_grade_blocking',
            field=models.BooleanField(default=False, help_text="Check True for technical or elective blocks that must run concurrently across the entire grade level. This is the single source of truth is_tech_subject() reads — set it here instead of relying on the subject's name or department, so a newly added subject never needs a code change to be routed through the shared-block / elective-splitting engine."),
        ),
        migrations.CreateModel(
            name='QuotaDefaultRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('Languages', 'Languages'), ('Mathematics', 'Mathematics'), ('Sciences', 'Sciences'), ('Humanities', 'Humanities'), ('Technical', 'Technical'), ('PE', 'Physical Education')], help_text="Leave blank to apply to any department — used for the blocked/synchronized-elective defaults, which don't vary by department. Set a specific department for a standalone-subject default.", max_length=50)),
                ('grade_band', models.CharField(choices=[('LOWER_PRIMARY', 'Lower Primary (Grades 1-3)'), ('UPPER_PRIMARY', 'Upper Primary (Grades 4-6)'), ('JUNIOR_SECONDARY', 'Junior Secondary (Grades 7-9)'), ('SENIOR_SCHOOL', 'Senior School (Grade 10+)')], max_length=20)),
                ('applies_when_blocked', models.BooleanField(default=False, help_text='Check for the figures that apply when the subject sits in a synchronized SubjectBlock for this grade (e.g. Technical/elective option blocks) — leave unchecked for the standalone-subject figures.')),
                ('total_lessons', models.PositiveIntegerField(default=0)),
                ('double_lessons_required', models.PositiveIntegerField(default=0)),
                ('remedial_lessons_required', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['department', 'grade_band'],
                'unique_together': {('department', 'grade_band', 'applies_when_blocked')},
            },
        ),
    ]
