# Generated by Django 6.0.1 on 2026-07-31 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0088_subject_synchronized_blocking_min_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Optional display name (e.g. 'Pure Sciences Combo 1'). Auto-derived from the subjects if left blank.", max_length=150)),
                ('code', models.CharField(blank=True, help_text='Optional official KNEC combination code/number, if published.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to retire a combination (e.g. the school stopped offering it) without deleting historical student selections that reference it.')),
                ('subjects', models.ManyToManyField(related_name='preset_combinations', to='school.subject')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_combinations', to='school.track')),
            ],
            options={
                'ordering': ['track', 'name'],
            },
        ),
        migrations.AddField(
            model_name='studentpathwayselection',
            name='preset_combination',
            field=models.ForeignKey(blank=True, help_text="The student's chosen pre-approved 3-subject combination for `track`, if any. Approving a selection with this set also approves the combination's 3 subjects as the student's elective StudentSubjectEnrollment rows — see api_decide_pathway_request.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_selections', to='school.presetcombination'),
        ),
    ]
