# Generated by Django 6.0.1 on 2026-07-31 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0089_presetcombination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(blank=True, help_text="Optional short code, e.g. 'SCI'.", max_length=10, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive departments stay on existing subjects but drop out of pickers for new ones.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        # NOTE: hand-edited from the autogenerated AlterField operations below. Postgres's
        # in-place ALTER COLUMN ... TYPE bigint USING "department"::bigint fails on any
        # existing non-numeric text (e.g. 'Technical', 'Humanities', or the literal string
        # 'None' some rows had) — RemoveField+AddField drops the old text column and adds a
        # fresh nullable FK column instead, with no cast attempted. This is safe: the old
        # string values are re-applied from a hardcoded snapshot by
        # `python manage.py backfill_departments`, run once after this migration.
        migrations.RemoveField(model_name='quotadefaultrule', name='department'),
        migrations.RemoveField(model_name='subject', name='department'),
        migrations.RemoveField(model_name='subjectcategorylimit', name='department'),
        migrations.AddField(
            model_name='quotadefaultrule',
            name='department',
            field=models.ForeignKey(blank=True, help_text="Leave blank to apply to any department — used for the blocked/synchronized-elective defaults, which don't vary by department. Set a specific department for a standalone-subject default.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quota_default_rules', to='school.department'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Leave blank for an uncategorized subject — set it from the Academics Hub.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='school.department'),
        ),
        migrations.AddField(
            model_name='subjectcategorylimit',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_limits', to='school.department'),
        ),
    ]
