# Hand-written -- NOT autogenerated. Track B step 2: paired with
# apps/core/migrations/0001_initial.py, which creates BackgroundJob and
# SystemAuditLog in `core`'s migration state (with Meta.db_table pinned to
# their original table names). This migration removes the same two models
# from `school`'s migration state -- database_operations is empty, so this
# issues zero SQL. The Python model classes themselves were deleted from
# school/models/jobs_models.py and school/models/classSubjects_models.py in
# the same change; they now live in apps/core/models.py.
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0091_department_curriculum'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name='BackgroundJob'),
                migrations.DeleteModel(name='SystemAuditLog'),
            ],
        ),
    ]
