# Hand-written -- NOT autogenerated. Track B step 3: paired with
# apps/messaging/migrations/0001_initial.py, which creates Notice, Event,
# Notification, ChatUserProfile, ChatThread, ThreadParticipant, MessageAudit,
# and ChatActionResponse in `messaging`'s migration state (Meta.db_table
# pinned to each model's original table name). This migration removes the
# same eight models from `school`'s migration state -- database_operations is
# empty, so this issues zero SQL. The exact state_operations sequence below
# (RemoveField before DeleteModel, in this order) was taken verbatim from
# `manage.py makemigrations messaging school --dry-run -v 3` -- Django's own
# autodetector, not hand-guessed -- since these 8 models have real FK
# interdependencies among themselves (ChatThread <- ThreadParticipant/
# MessageAudit <- ChatActionResponse) and this is the order Django itself
# proved keeps the migration state internally consistent at every step.
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0092_move_core_models_to_apps_core'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='chatactionresponse',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='chatactionresponse',
                    name='message',
                ),
                migrations.RemoveField(
                    model_name='chatactionresponse',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='chatthread',
                    name='related_student',
                ),
                migrations.RemoveField(
                    model_name='messageaudit',
                    name='thread',
                ),
                migrations.RemoveField(
                    model_name='threadparticipant',
                    name='thread',
                ),
                migrations.RemoveField(
                    model_name='chatuserprofile',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='Event',
                ),
                migrations.RemoveField(
                    model_name='messageaudit',
                    name='sender',
                ),
                migrations.DeleteModel(
                    name='Notice',
                ),
                migrations.RemoveField(
                    model_name='notification',
                    name='recipient',
                ),
                migrations.AlterUniqueTogether(
                    name='threadparticipant',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='threadparticipant',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='ChatActionResponse',
                ),
                migrations.DeleteModel(
                    name='ChatThread',
                ),
                migrations.DeleteModel(
                    name='ChatUserProfile',
                ),
                migrations.DeleteModel(
                    name='MessageAudit',
                ),
                migrations.DeleteModel(
                    name='Notification',
                ),
                migrations.DeleteModel(
                    name='ThreadParticipant',
                ),
            ],
        ),
    ]
