# Hand-written -- NOT autogenerated. Track B step 4: paired with
# apps/attendance/migrations/0001_initial.py and
# apps/assignments/migrations/0001_initial.py, which create
# AttendanceSession/AttendanceRecord and the 9 assignments models in their
# new apps' migration state. This migration removes the same 11 models from
# `school`'s state -- database_operations is empty, so this issues zero SQL.
# The exact state_operations sequence below (RemoveField/AlterUniqueTogether
# before DeleteModel, in this order) was taken verbatim from
# `manage.py makemigrations attendance assignments school --dry-run -v3` --
# Django's own autodetector, not hand-guessed -- since these 11 models have
# real FK interdependencies among themselves (Assignment <- Question/
# AssignmentGroup/StudentSubmission <- StudentAnswer <- CriterionScore, and
# AttendanceSession <- AttendanceRecord).
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0093_move_messaging_models_to_apps_messaging'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='assignment',
                    name='additional_class_streams',
                ),
                migrations.RemoveField(
                    model_name='assignment',
                    name='assigned_students',
                ),
                migrations.RemoveField(
                    model_name='assignment',
                    name='class_stream',
                ),
                migrations.RemoveField(
                    model_name='assignment',
                    name='subject',
                ),
                migrations.RemoveField(
                    model_name='assignment',
                    name='teacher',
                ),
                migrations.RemoveField(
                    model_name='assignment',
                    name='term',
                ),
                migrations.RemoveField(
                    model_name='studentsubmission',
                    name='assignment',
                ),
                migrations.RemoveField(
                    model_name='question',
                    name='assignment',
                ),
                migrations.RemoveField(
                    model_name='assignmentgroup',
                    name='assignment',
                ),
                migrations.RemoveField(
                    model_name='assignmentgroup',
                    name='members',
                ),
                migrations.AlterUniqueTogether(
                    name='attendancerecord',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='attendancerecord',
                    name='session',
                ),
                migrations.RemoveField(
                    model_name='attendancerecord',
                    name='student',
                ),
                migrations.AlterUniqueTogether(
                    name='attendancesession',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='attendancesession',
                    name='class_stream',
                ),
                migrations.RemoveField(
                    model_name='attendancesession',
                    name='submitted_by',
                ),
                migrations.AlterUniqueTogether(
                    name='criterionscore',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='criterionscore',
                    name='answer',
                ),
                migrations.RemoveField(
                    model_name='criterionscore',
                    name='criterion',
                ),
                migrations.RemoveField(
                    model_name='rubriccriterion',
                    name='question',
                ),
                migrations.RemoveField(
                    model_name='studentanswer',
                    name='question',
                ),
                migrations.RemoveField(
                    model_name='questionoption',
                    name='question',
                ),
                migrations.RemoveField(
                    model_name='studentanswer',
                    name='selected_options',
                ),
                migrations.RemoveField(
                    model_name='studentanswer',
                    name='submission',
                ),
                migrations.AlterUniqueTogether(
                    name='studentsubmission',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='studentsubmission',
                    name='student',
                ),
                migrations.DeleteModel(
                    name='AssignmentAttachment',
                ),
                migrations.DeleteModel(
                    name='Assignment',
                ),
                migrations.DeleteModel(
                    name='AssignmentGroup',
                ),
                migrations.DeleteModel(
                    name='AttendanceRecord',
                ),
                migrations.DeleteModel(
                    name='AttendanceSession',
                ),
                migrations.DeleteModel(
                    name='CriterionScore',
                ),
                migrations.DeleteModel(
                    name='RubricCriterion',
                ),
                migrations.DeleteModel(
                    name='Question',
                ),
                migrations.DeleteModel(
                    name='QuestionOption',
                ),
                migrations.DeleteModel(
                    name='StudentAnswer',
                ),
                migrations.DeleteModel(
                    name='StudentSubmission',
                ),
            ],
        ),
    ]
