# Hand-written -- NOT autogenerated. Track B step 5: paired with
# apps/students/migrations/0001_initial.py and
# apps/staff/migrations/0001_initial.py, which create StudentTask/
# StudentPathwaySelection/StudentSubjectEnrollment and TeacherLeave/
# LongTermReliefAssignment/TeacherStructuralAvailability in their new apps'
# migration state. This migration removes the same 6 models from `school`'s
# state -- database_operations is empty, so this issues zero SQL. The exact
# state_operations sequence below (RemoveField/AlterUniqueTogether before
# DeleteModel, in this order) was taken verbatim from
# `manage.py makemigrations students staff school --dry-run -v3` -- Django's
# own autodetector, not hand-guessed -- since LongTermReliefAssignment FKs to
# TeacherLeave and StudentPathwaySelection/StudentSubjectEnrollment FK to
# several academics-domain models still living in `school`.
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0094_move_attendance_assignments_models_to_apps'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='studentpathwayselection',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='studentpathwayselection',
                    name='academic_year',
                ),
                migrations.RemoveField(
                    model_name='studentpathwayselection',
                    name='pathway',
                ),
                migrations.RemoveField(
                    model_name='studentpathwayselection',
                    name='preset_combination',
                ),
                migrations.RemoveField(
                    model_name='studentpathwayselection',
                    name='student',
                ),
                migrations.RemoveField(
                    model_name='studentpathwayselection',
                    name='track',
                ),
                migrations.AlterUniqueTogether(
                    name='studentsubjectenrollment',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='studentsubjectenrollment',
                    name='academic_year',
                ),
                migrations.RemoveField(
                    model_name='studentsubjectenrollment',
                    name='student',
                ),
                migrations.RemoveField(
                    model_name='studentsubjectenrollment',
                    name='subject',
                ),
                migrations.RemoveField(
                    model_name='studenttask',
                    name='student',
                ),
                migrations.RemoveField(
                    model_name='teacherleave',
                    name='teacher',
                ),
                migrations.AlterUniqueTogether(
                    name='teacherstructuralavailability',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='teacherstructuralavailability',
                    name='teacher',
                ),
                migrations.RemoveField(
                    model_name='teacherstructuralavailability',
                    name='time_slot',
                ),
                migrations.DeleteModel(
                    name='LongTermReliefAssignment',
                ),
                migrations.DeleteModel(
                    name='StudentPathwaySelection',
                ),
                migrations.DeleteModel(
                    name='StudentSubjectEnrollment',
                ),
                migrations.DeleteModel(
                    name='StudentTask',
                ),
                migrations.DeleteModel(
                    name='TeacherLeave',
                ),
                migrations.DeleteModel(
                    name='TeacherStructuralAvailability',
                ),
            ],
        ),
    ]
