# Hand-written -- NOT autogenerated. Track B step 6 (highest-risk pair):
# paired with apps/allocations/migrations/0001_initial.py and
# apps/timetable/migrations/0001_initial.py, which create the 7 allocations
# models and 4 timetable models in their new apps' migration state. This
# migration removes the same 11 models from `school`'s state --
# database_operations is empty, so this issues zero SQL. The exact
# state_operations sequence below (RemoveField/AlterUniqueTogether before
# DeleteModel, in this order) was taken verbatim from
# `manage.py makemigrations allocations timetable school --dry-run -v3` --
# Django's own autodetector, not hand-guessed -- since these 11 models have
# extensive FK interdependencies among themselves and with still-in-`school`
# academics models (GradeLevel, Subject, Department, ClassStream).
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0095_move_students_staff_models_to_apps'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='allocationpublishstate',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='allocationpublishstate',
                    name='academic_year',
                ),
                migrations.RemoveField(
                    model_name='allocationpublishstate',
                    name='classroom',
                ),
                migrations.RemoveField(
                    model_name='allocationpublishstate',
                    name='published_by',
                ),
                migrations.RemoveField(
                    model_name='allocationpublishstate',
                    name='term',
                ),
                migrations.AlterUniqueTogether(
                    name='dailycover',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='dailycover',
                    name='absent_teacher',
                ),
                migrations.RemoveField(
                    model_name='dailycover',
                    name='covering_teacher',
                ),
                migrations.RemoveField(
                    model_name='dailycover',
                    name='target_lesson',
                ),
                migrations.DeleteModel(
                    name='GlobalAllocationPolicy',
                ),
                migrations.AlterUniqueTogether(
                    name='lessonallocation',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='lessonallocation',
                    name='class_stream',
                ),
                migrations.RemoveField(
                    model_name='lessonallocation',
                    name='subject',
                ),
                migrations.RemoveField(
                    model_name='lessonallocation',
                    name='teacher',
                ),
                migrations.RemoveField(
                    model_name='lessonallocation',
                    name='time_slot',
                ),
                migrations.RemoveField(
                    model_name='lessonallocation',
                    name='timetable',
                ),
                migrations.AlterUniqueTogether(
                    name='quotadefaultrule',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='quotadefaultrule',
                    name='department',
                ),
                migrations.AlterUniqueTogether(
                    name='subjectallocation',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='subjectallocation',
                    name='academic_year',
                ),
                migrations.RemoveField(
                    model_name='subjectallocation',
                    name='classroom',
                ),
                migrations.RemoveField(
                    model_name='subjectallocation',
                    name='subject',
                ),
                migrations.RemoveField(
                    model_name='subjectallocation',
                    name='teacher',
                ),
                migrations.RemoveField(
                    model_name='subjectallocation',
                    name='term',
                ),
                migrations.AlterUniqueTogether(
                    name='subjectblock',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='subjectblock',
                    name='academic_year',
                ),
                migrations.RemoveField(
                    model_name='subjectblock',
                    name='grade_level',
                ),
                migrations.RemoveField(
                    model_name='subjectblock',
                    name='subjects',
                ),
                migrations.RemoveField(
                    model_name='subjectblock',
                    name='term',
                ),
                migrations.AlterUniqueTogether(
                    name='subjectquota',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='subjectquota',
                    name='grade',
                ),
                migrations.RemoveField(
                    model_name='subjectquota',
                    name='subject',
                ),
                migrations.AlterUniqueTogether(
                    name='subjectsplittingrule',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='subjectsplittingrule',
                    name='grade',
                ),
                migrations.RemoveField(
                    model_name='subjectsplittingrule',
                    name='last_modified_by',
                ),
                migrations.RemoveField(
                    model_name='subjectsplittingrule',
                    name='subject',
                ),
                migrations.RemoveField(
                    model_name='timetable',
                    name='academic_year',
                ),
                migrations.RemoveField(
                    model_name='timetable',
                    name='term',
                ),
                migrations.DeleteModel(
                    name='TimetablePedagogyPolicy',
                ),
                migrations.DeleteModel(
                    name='AllocationPublishState',
                ),
                migrations.DeleteModel(
                    name='DailyCover',
                ),
                migrations.DeleteModel(
                    name='LessonAllocation',
                ),
                migrations.DeleteModel(
                    name='QuotaDefaultRule',
                ),
                migrations.DeleteModel(
                    name='SubjectAllocation',
                ),
                migrations.DeleteModel(
                    name='SubjectBlock',
                ),
                migrations.DeleteModel(
                    name='SubjectQuota',
                ),
                migrations.DeleteModel(
                    name='SubjectSplittingRule',
                ),
                migrations.DeleteModel(
                    name='Timetable',
                ),
            ],
        ),
    ]
