# Hand-written -- NOT autogenerated. Track B step 8 (the largest single Track B
# relocation): paired with apps/academics/migrations/0001_initial.py, which
# creates all 18 academics models in their new app's migration state. This
# migration removes the same 18 models from `school`'s state --
# database_operations is empty, so this issues zero SQL. Also includes the
# two same-app fields that keep pointing at a relocated model (StudentExtra.cl
# -> ClassStream, TeacherExtra.qualified_subjects -> Subject) as AlterField
# operations updating their `to=` app_label -- no physical column/table change,
# since Meta.db_table pins every academics table name.
#
# This migration must be sequenced AFTER every dependent app's own
# `0002_alter_*` migration (allocations, assignments, attendance, exams,
# results, staff, students, timetable) -- each of those updates that app's own
# FK fields' `to=` from `school.<model>` to `academics.<model>` first, so that
# by the time these 18 models are deleted from `school`'s state here, no other
# app's recorded migration state still points at a `school.<model>` that no
# longer exists.
#
# The exact state_operations sequence below (RemoveField/AlterUniqueTogether/
# AlterField before each DeleteModel, in this order) was taken verbatim from
# `manage.py makemigrations academics --dry-run -v3` -- Django's own
# autodetector, not hand-guessed -- since these 18 models have extensive FK
# interdependencies among themselves and with still-in-`school` identity data
# (StudentExtra.cl, TeacherExtra.qualified_subjects, ClassStream.class_teacher).
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('allocations', '0002_alter_allocationpublishstate_academic_year_and_more'),
        ('assignments', '0002_alter_assignment_additional_class_streams_and_more'),
        ('attendance', '0002_alter_attendancesession_class_stream'),
        ('exams', '0002_alter_classexamstatus_class_stream_and_more'),
        ('results', '0002_alter_classperformanceanalytics_class_stream_and_more'),
        ('school', '0097_move_exams_results_models_to_apps'),
        ('staff', '0002_alter_teacherstructuralavailability_time_slot'),
        ('students', '0002_alter_studentpathwayselection_academic_year_and_more'),
        ('timetable', '0002_alter_lessonallocation_class_stream_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='examterm',
                    name='academic_year',
                ),
                migrations.AlterUniqueTogether(
                    name='classstream',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='classstream',
                    name='class_teacher',
                ),
                migrations.RemoveField(
                    model_name='classstream',
                    name='grade',
                ),
                migrations.AlterField(
                    model_name='studentextra',
                    name='cl',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.classstream', verbose_name='Class'),
                ),
                migrations.RemoveField(
                    model_name='pathway',
                    name='curriculum',
                ),
                migrations.RemoveField(
                    model_name='department',
                    name='curriculum',
                ),
                migrations.RemoveField(
                    model_name='gradelevel',
                    name='curriculum',
                ),
                migrations.RemoveField(
                    model_name='curriculumpreset',
                    name='curriculum',
                ),
                migrations.RemoveField(
                    model_name='tier',
                    name='curriculum',
                ),
                migrations.RemoveField(
                    model_name='subjectcurriculumprofile',
                    name='curriculum',
                ),
                migrations.RemoveField(
                    model_name='curriculumpreset',
                    name='pathway',
                ),
                migrations.RemoveField(
                    model_name='curriculumpreset',
                    name='tier',
                ),
                migrations.RemoveField(
                    model_name='curriculumpreset',
                    name='track',
                ),
                migrations.RemoveField(
                    model_name='subjectpool',
                    name='preset',
                ),
                migrations.AlterUniqueTogether(
                    name='department',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='subject',
                    name='department',
                ),
                migrations.RemoveField(
                    model_name='subjectcurriculumprofile',
                    name='department',
                ),
                migrations.RemoveField(
                    model_name='subjectcategorylimit',
                    name='department',
                ),
                migrations.RemoveField(
                    model_name='gradelevel',
                    name='tier',
                ),
                migrations.RemoveField(
                    model_name='subjectcategorylimit',
                    name='grade',
                ),
                migrations.RemoveField(
                    model_name='subjectselectionrule',
                    name='grade',
                ),
                migrations.RemoveField(
                    model_name='subjectexclusionrule',
                    name='grade',
                ),
                migrations.AlterUniqueTogether(
                    name='pathway',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='track',
                    name='pathway',
                ),
                migrations.RemoveField(
                    model_name='presetcombination',
                    name='subjects',
                ),
                migrations.RemoveField(
                    model_name='presetcombination',
                    name='track',
                ),
                migrations.RemoveField(
                    model_name='subjectexclusionrule',
                    name='subject_b',
                ),
                migrations.RemoveField(
                    model_name='subjectpool',
                    name='subjects',
                ),
                migrations.RemoveField(
                    model_name='subjectcurriculumprofile',
                    name='subject',
                ),
                migrations.RemoveField(
                    model_name='subjectexclusionrule',
                    name='subject_a',
                ),
                migrations.AlterUniqueTogether(
                    name='subjectcategorylimit',
                    unique_together=None,
                ),
                migrations.AlterUniqueTogether(
                    name='subjectcurriculumprofile',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='subjectcurriculumprofile',
                    name='tier',
                ),
                migrations.AlterUniqueTogether(
                    name='subjectexclusionrule',
                    unique_together=None,
                ),
                migrations.AlterUniqueTogether(
                    name='subjectpool',
                    unique_together=None,
                ),
                migrations.AlterUniqueTogether(
                    name='tier',
                    unique_together=None,
                ),
                migrations.DeleteModel(
                    name='TimeSlot',
                ),
                migrations.AlterUniqueTogether(
                    name='track',
                    unique_together=None,
                ),
                migrations.AlterField(
                    model_name='teacherextra',
                    name='qualified_subjects',
                    field=models.ManyToManyField(blank=True, related_name='qualified_teachers', to='academics.subject'),
                ),
                migrations.DeleteModel(
                    name='AcademicYear',
                ),
                migrations.DeleteModel(
                    name='ExamTerm',
                ),
                migrations.DeleteModel(
                    name='ClassStream',
                ),
                migrations.DeleteModel(
                    name='Curriculum',
                ),
                migrations.DeleteModel(
                    name='CurriculumPreset',
                ),
                migrations.DeleteModel(
                    name='Department',
                ),
                migrations.DeleteModel(
                    name='SubjectCategoryLimit',
                ),
                migrations.DeleteModel(
                    name='SubjectSelectionRule',
                ),
                migrations.DeleteModel(
                    name='GradeLevel',
                ),
                migrations.DeleteModel(
                    name='Pathway',
                ),
                migrations.DeleteModel(
                    name='PresetCombination',
                ),
                migrations.DeleteModel(
                    name='Track',
                ),
                migrations.DeleteModel(
                    name='SubjectPool',
                ),
                migrations.DeleteModel(
                    name='Subject',
                ),
                migrations.DeleteModel(
                    name='SubjectExclusionRule',
                ),
                migrations.DeleteModel(
                    name='SubjectCurriculumProfile',
                ),
                migrations.DeleteModel(
                    name='Tier',
                ),
            ],
        ),
    ]
