# Generated by Django 6.0.1 on 2026-08-02 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_classstream_class_teacher'),
        ('allocations', '0003_alter_subjectallocation_teacher'),
        ('assignments', '0003_alter_assignment_assigned_students_and_more'),
        ('attendance', '0003_alter_attendancerecord_student'),
        ('exams', '0003_alter_examresult_student_alter_examresult_teacher_and_more'),
        ('messaging', '0002_alter_chatthread_related_student'),
        ('results', '0003_alter_studenttermresult_student_and_more'),
        ('school', '0098_move_academics_models_to_apps'),
        ('staff', '0003_alter_longtermreliefassignment_absent_teacher_and_more'),
        ('students', '0003_alter_studentpathwayselection_student_and_more'),
        ('timetable', '0003_alter_dailycover_absent_teacher_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='admininvitecode',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='admininvitecode',
                    name='revoked_by',
                ),
                migrations.RemoveField(
                    model_name='admininvitecode',
                    name='used_by',
                ),
                migrations.RemoveField(
                    model_name='forcedpasswordchange',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='parentextra',
                    name='students',
                ),
                migrations.RemoveField(
                    model_name='parentextra',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='role',
                    name='permissions',
                ),
                migrations.RemoveField(
                    model_name='staffextra',
                    name='requested_role',
                ),
                migrations.RemoveField(
                    model_name='userrole',
                    name='role',
                ),
                migrations.RemoveField(
                    model_name='staffextra',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='studentextra',
                    name='cl',
                ),
                migrations.RemoveField(
                    model_name='studentextra',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='teacherextra',
                    name='qualified_subjects',
                ),
                migrations.RemoveField(
                    model_name='teacherextra',
                    name='user',
                ),
                migrations.AlterUniqueTogether(
                    name='userrole',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='userrole',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='AdminExtra',
                ),
                migrations.DeleteModel(
                    name='AdminInviteCode',
                ),
                migrations.DeleteModel(
                    name='ForcedPasswordChange',
                ),
                migrations.DeleteModel(
                    name='ParentExtra',
                ),
                migrations.DeleteModel(
                    name='Permission',
                ),
                migrations.DeleteModel(
                    name='Role',
                ),
                migrations.DeleteModel(
                    name='StaffExtra',
                ),
                migrations.DeleteModel(
                    name='StudentExtra',
                ),
                migrations.DeleteModel(
                    name='TeacherExtra',
                ),
                migrations.DeleteModel(
                    name='UserRole',
                ),
            ],
            database_operations=[]
        )
    ]
