# Generated by Django 6.0.1 on 2026-08-01 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('PRE_PRIMARY', 'Pre-Primary'), ('PRIMARY', 'Primary (Lower + Upper)'), ('JSS', 'Junior School'), ('SENIOR', 'Senior School'), ('COMBINED', 'Combined / Multiple levels under one administration')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shares_compound_with', models.ForeignKey(blank=True, help_text='Another School row this one physically shares a compound with, while remaining administratively separate (e.g. a JSS row pointing at its co-located primary school).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_located_schools', to='identity.school')),
            ],
            options={
                'db_table': 'identity_school',
            },
        ),
    ]
