# Generated by Django 6.0.1 on 2026-08-02 18:45

import django.db.models.deletion
import school.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Permission',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('code', models.CharField(help_text="e.g. 'curriculum.edit'", max_length=100, unique=True)),
                        ('label', models.CharField(max_length=150)),
                        ('module', models.CharField(help_text="Groups permissions in the UI, e.g. 'Curriculum'", max_length=50)),
                    ],
                    options={
                        'db_table': 'school_permission',
                        'ordering': ['module', 'code'],
                    },
                ),
                migrations.CreateModel(
                    name='AdminExtra',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('mobile', models.CharField(max_length=40, null=True)),
                        ('address', models.CharField(max_length=200, null=True)),
                        ('status', models.BooleanField(default=False)),
                        ('verification_code', models.CharField(blank=True, max_length=128, null=True)),
                        ('code_generated_at', models.DateTimeField(blank=True, null=True)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'school_adminextra',
                    },
                ),
                migrations.CreateModel(
                    name='AdminInviteCode',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('code_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                        ('code_preview', models.CharField(max_length=4)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('expires_at', models.DateTimeField()),
                        ('used_at', models.DateTimeField(blank=True, null=True)),
                        ('revoked_at', models.DateTimeField(blank=True, null=True)),
                        ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_admin_invites', to=settings.AUTH_USER_MODEL)),
                        ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                        ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'school_admininvitecode',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='ForcedPasswordChange',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forced_password_change', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'school_forcedpasswordchange',
                    },
                ),
                migrations.CreateModel(
                    name='Role',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100, unique=True)),
                        ('description', models.CharField(blank=True, max_length=255)),
                        ('is_system_role', models.BooleanField(default=False)),
                        ('permissions', models.ManyToManyField(blank=True, db_table='school_role_permissions', related_name='roles', to='identity.permission')),
                    ],
                    options={
                        'db_table': 'school_role',
                    },
                ),
                migrations.CreateModel(
                    name='StaffExtra',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('job_title', models.CharField(blank=True, help_text="e.g. 'Librarian', 'Finance Officer' — display only, doesn't grant access on its own.", max_length=100)),
                        ('id_number', models.CharField(blank=True, max_length=20, null=True)),
                        ('mobile', models.CharField(blank=True, max_length=40)),
                        ('address', models.CharField(blank=True, max_length=255, null=True)),
                        ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/Staff/', validators=[school.validators.profile_pic_validator])),
                        ('joindate', models.DateField(auto_now_add=True)),
                        ('status', models.BooleanField(default=False)),
                        ('requested_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_applicants', to='identity.role')),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'school_staffextra',
                    },
                ),
                migrations.CreateModel(
                    name='StudentExtra',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('roll', models.CharField(max_length=20, unique=True)),
                        ('mobile', models.CharField(blank=True, max_length=40, null=True)),
                        ('address', models.CharField(max_length=255, null=True)),
                        ('fee', models.PositiveIntegerField(null=True)),
                        ('status', models.BooleanField(default=False)),
                        ('parent_name', models.CharField(max_length=100, null=True)),
                        ('parent_mobile', models.CharField(max_length=40, null=True)),
                        ('family_structure', models.CharField(blank=True, choices=[('both', 'Both Parents'), ('single', 'Single Parent'), ('guardian', 'Guardian')], max_length=10, null=True)),
                        ('single_parent_type', models.CharField(blank=True, choices=[('Mother', 'Mother'), ('Father', 'Father')], max_length=10, null=True)),
                        ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                        ('father_mobile', models.CharField(blank=True, max_length=40, null=True)),
                        ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                        ('mother_mobile', models.CharField(blank=True, max_length=40, null=True)),
                        ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                        ('guardian_mobile', models.CharField(blank=True, max_length=40, null=True)),
                        ('guardian_relationship', models.CharField(blank=True, max_length=50, null=True)),
                        ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/Student/', validators=[school.validators.profile_pic_validator])),
                        ('enrollment_state', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Expelled', 'Expelled'), ('Transferred', 'Transferred Out')], default='Active', max_length=20)),
                        ('enrollment_notes', models.TextField(blank=True, help_text='Reason for suspension/expulsion/transfer', null=True)),
                        ('last_enrollment_change', models.DateTimeField(auto_now=True, null=True)),
                        ('cl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.classstream', verbose_name='Class')),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'school_studentextra',
                    },
                ),
                migrations.CreateModel(
                    name='ParentExtra',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('mobile', models.CharField(max_length=40)),
                        ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian'), ('Other', 'Other')], default='Father', max_length=20)),
                        ('status', models.BooleanField(default=False)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                        ('students', models.ManyToManyField(db_table='school_parentextra_students', to='identity.studentextra')),
                    ],
                    options={
                        'db_table': 'school_parentextra',
                    },
                ),
                migrations.CreateModel(
                    name='TeacherExtra',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('id_number', models.CharField(max_length=20, null=True)),
                        ('address', models.CharField(max_length=255, null=True)),
                        ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/Teacher/', validators=[school.validators.profile_pic_validator])),
                        ('subjects', models.CharField(blank=True, max_length=255, null=True)),
                        ('mobile', models.CharField(max_length=40)),
                        ('joindate', models.DateField(auto_now_add=True)),
                        ('status', models.BooleanField(default=False)),
                        ('salary', models.PositiveIntegerField(blank=True, default=0, null=True)),
                        ('qualified_subjects', models.ManyToManyField(blank=True, db_table='school_teacherextra_qualified_subjects', related_name='qualified_teachers', to='academics.subject')),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'school_teacherextra',
                    },
                ),
                migrations.CreateModel(
                    name='UserRole',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('assigned_at', models.DateTimeField(auto_now_add=True)),
                        ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='identity.role')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbac_roles', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'school_userrole',
                        'unique_together': {('user', 'role')},
                    },
                ),
            ],
            database_operations=[]
        )
    ]
