# Generated by Django 6.0.1 on 2026-08-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_permission_adminextra_admininvitecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='enrollment_state',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Expelled', 'Expelled'), ('Transferred', 'Transferred Out'), ('Graduated', 'Graduated')], default='Active', max_length=20),
        ),
    ]
