# Generated by Django 6.0.1 on 2026-09-03 10:21

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_role_school'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        TrigramExtension(),
        migrations.RunSQL(
            sql="CREATE INDEX auth_user_first_name_trgm ON auth_user USING gin (first_name gin_trgm_ops);",
            reverse_sql="DROP INDEX auth_user_first_name_trgm;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX auth_user_last_name_trgm ON auth_user USING gin (last_name gin_trgm_ops);",
            reverse_sql="DROP INDEX auth_user_last_name_trgm;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX auth_user_username_trgm ON auth_user USING gin (username gin_trgm_ops);",
            reverse_sql="DROP INDEX auth_user_username_trgm;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX auth_user_email_trgm ON auth_user USING gin (email gin_trgm_ops);",
            reverse_sql="DROP INDEX auth_user_email_trgm;",
        ),
    ]
