# Generated by Django 6.0.7 on 2026-09-04 10:06

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_academicyear_is_active_and_more'),
        ('identity', '0008_auth_user_trigram_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminextra',
            name='mobile',
            field=models.CharField(db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='adminextra',
            name='status',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='admininvitecode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='admininvitecode',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='parentextra',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='parentextra',
            name='mobile',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='parentextra',
            name='status',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='label',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(db_index=True, help_text="Groups permissions in the UI, e.g. 'Curriculum'", max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Delegation tier. Lower ranks outrank higher ones. Null means unranked -- cannot be granted or managed by anyone except a superuser.', null=True),
        ),
        migrations.AlterField(
            model_name='staffextra',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffextra',
            name='job_title',
            field=models.CharField(blank=True, db_index=True, help_text="e.g. 'Librarian', 'Finance Officer' — display only, doesn't grant access on its own.", max_length=100),
        ),
        migrations.AlterField(
            model_name='staffextra',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='staffextra',
            name='status',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='enrollment_state',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Expelled', 'Expelled'), ('Transferred', 'Transferred Out'), ('Graduated', 'Graduated')], db_index=True, default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='status',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='teacherextra',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherextra',
            name='mobile',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='teacherextra',
            name='status',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='studentextra',
            index=django.contrib.postgres.indexes.GinIndex(fields=['roll'], name='studentextra_roll_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
