# Hand-written -- NOT autogenerated. Track B step 5: state-only relocation of
# StudentTask, StudentPathwaySelection, and StudentSubjectEnrollment into the
# `students` app. database_operations is empty, so this issues zero SQL --
# it only tells Django's migration state that these three models now belong
# to `students`. The physical tables (pinned via Meta.db_table in
# apps/students/models.py) never move. The exact CreateModel field reprs
# below were taken verbatim from
# `manage.py makemigrations students staff school --dry-run -v3` -- Django's
# own autodetector, not hand-transcribed -- to guarantee zero drift against
# `makemigrations --check`. Paired with
# school/migrations/0095_move_students_staff_models_to_apps.py, which deletes
# the same three models from `school`'s state, also with
# database_operations=[].
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0095_move_students_staff_models_to_apps'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='StudentTask',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=255)),
                        ('due_date', models.DateField(blank=True, null=True)),
                        ('is_done', models.BooleanField(default=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='school.studentextra')),
                    ],
                    options={
                        'db_table': 'school_studenttask',
                        'ordering': ['is_done', 'due_date', '-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='StudentPathwaySelection',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved & Locked'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear')),
                        ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='school.pathway')),
                        ('preset_combination', models.ForeignKey(blank=True, help_text="The student's chosen pre-approved 3-subject combination for `track`, if any. Approving a selection with this set also approves the combination's 3 subjects as the student's elective StudentSubjectEnrollment rows — see api_decide_pathway_request.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_selections', to='school.presetcombination')),
                        ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_selections', to='school.studentextra')),
                        ('track', models.ForeignKey(blank=True, help_text='Required whenever the chosen Pathway has Tracks configured — see api_student_pathway_request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_selections', to='school.track')),
                    ],
                    options={
                        'db_table': 'school_studentpathwayselection',
                        'unique_together': {('student', 'academic_year')},
                    },
                ),
                migrations.CreateModel(
                    name='StudentSubjectEnrollment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('status', models.CharField(choices=[('Pending', 'Pending Admin Approval'), ('Approved', 'Approved & Locked'), ('Rejected', 'Rejected by Admin')], default='Pending', max_length=20)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear')),
                        ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='school.studentextra')),
                        ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
                    ],
                    options={
                        'db_table': 'school_studentsubjectenrollment',
                        'unique_together': {('student', 'subject', 'academic_year')},
                    },
                ),
            ],
        ),
    ]
