# Hand-written -- NOT autogenerated. Track B step 8 side-effect -- see
# apps/allocations/migrations/0002_alter_allocationpublishstate_academic_year_and_more.py
# for the full explanation (same class of change: `to=` app_label update
# only, database_operations=[], zero SQL). Verbatim from
# `manage.py makemigrations academics --dry-run -v3`.
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='studentpathwayselection',
                    name='academic_year',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
                ),
                migrations.AlterField(
                    model_name='studentpathwayselection',
                    name='pathway',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='academics.pathway'),
                ),
                migrations.AlterField(
                    model_name='studentpathwayselection',
                    name='preset_combination',
                    field=models.ForeignKey(blank=True, help_text="The student's chosen pre-approved 3-subject combination for `track`, if any. Approving a selection with this set also approves the combination's 3 subjects as the student's elective StudentSubjectEnrollment rows — see api_decide_pathway_request.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_selections', to='academics.presetcombination'),
                ),
                migrations.AlterField(
                    model_name='studentpathwayselection',
                    name='track',
                    field=models.ForeignKey(blank=True, help_text='Required whenever the chosen Pathway has Tracks configured — see api_student_pathway_request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_selections', to='academics.track'),
                ),
                migrations.AlterField(
                    model_name='studentsubjectenrollment',
                    name='academic_year',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
                ),
                migrations.AlterField(
                    model_name='studentsubjectenrollment',
                    name='subject',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
                ),
            ],
        ),
    ]
