# Generated by Django 6.0.1 on 2026-08-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_permission_adminextra_admininvitecode_and_more'),
        ('students', '0002_alter_studentpathwayselection_academic_year_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='studentpathwayselection',
                    name='student',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_selections', to='identity.studentextra'),
                ),
                migrations.AlterField(
                    model_name='studentsubjectenrollment',
                    name='student',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='identity.studentextra'),
                ),
                migrations.AlterField(
                    model_name='studenttask',
                    name='student',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='identity.studentextra'),
                ),
            ],
            database_operations=[]
        )
    ]
