# Generated by Django 6.0.1 on 2026-08-13 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_examterm_results_finalized_and_more'),
        ('identity', '0003_alter_studentextra_enrollment_state'),
        ('students', '0003_alter_studentpathwayselection_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_code', models.CharField(choices=[('KPSEA', 'KPSEA'), ('KJSEA', 'KJSEA'), ('KCSE', 'KCSE')], max_length=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.CharField(blank=True, help_text='Informational only — not used by any gating logic.', max_length=20)),
                ('destination', models.CharField(blank=True, help_text='Placement school (KJSEA) or university/institution (KCSE). Blank for KPSEA.', max_length=255)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='national_exam_records', to='identity.studentextra')),
            ],
            options={
                'db_table': 'school_nationalexamrecord',
                'unique_together': {('student', 'exam_code', 'academic_year')},
            },
        ),
    ]
