# Generated by Django 6.0.7 on 2026-09-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_nationalexamrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpathwayselection',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved & Locked'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentsubjectenrollment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Admin Approval'), ('Approved', 'Approved & Locked'), ('Rejected', 'Rejected by Admin')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='studenttask',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='studenttask',
            name='is_done',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
