# Generated by Django 6.0.7 on 2026-09-08 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_academicyear_is_active_and_more'),
        ('students', '0006_promotionevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionevent',
            name='created_pathway_selection',
            field=models.ForeignKey(blank=True, help_text='Set only if this promotion created a new StudentPathwaySelection row via _carry_forward_pathway_selection (SSS grades). Reverting deletes exactly this row and nothing else -- an already-existing selection for the target year is left untouched.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.studentpathwayselection'),
        ),
        migrations.AlterField(
            model_name='promotionevent',
            name='previous_cl',
            field=models.ForeignKey(blank=True, help_text="Student's class stream immediately before this promotion. Null for a 'graduated' outcome, since graduation doesn't reassign cl.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.classstream'),
        ),
    ]
