# Hand-written -- NOT autogenerated. Track B step 6: state-only relocation of
# TimetablePedagogyPolicy, Timetable, LessonAllocation, and DailyCover into
# the `timetable` app. database_operations is empty, so this issues zero
# SQL -- it only tells Django's migration state that these four models now
# belong to `timetable`. The physical tables (pinned via Meta.db_table in
# apps/timetable/models.py) never move. The exact CreateModel field reprs
# below were taken verbatim from
# `manage.py makemigrations allocations timetable school --dry-run -v3` --
# Django's own autodetector, not hand-transcribed. Paired with
# school/migrations/0096_move_allocations_timetable_models_to_apps.py, which
# deletes the same four models from `school`'s state, also with
# database_operations=[].
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0096_move_allocations_timetable_models_to_apps'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='TimetablePedagogyPolicy',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('enforcement_mode', models.CharField(choices=[('STRICT', 'Strict Hard Blocks (Prevent Saves)'), ('SOFT', 'Soft Enforcement (Allow Saves with Warnings)')], default='STRICT', max_length=10)),
                        ('max_consecutive_periods', models.PositiveIntegerField(default=3, help_text='Maximum lessons a teacher can handle back-to-back before a mandatory break.')),
                        ('max_daily_subject_frequency', models.PositiveIntegerField(default=2, help_text="Maximum times a single subject can appear in a classroom's daily schedule.")),
                        ('min_subject_spacing_periods', models.PositiveIntegerField(default=2, help_text='Minimum period gap required between two single lessons of the same subject on the same day.')),
                        ('allow_remedial_double_periods', models.BooleanField(default=False, help_text='If True, early morning or late evening remedial blocks can be linked as double periods.')),
                        ('heavy_day_threshold', models.PositiveIntegerField(default=5, help_text="The number of lessons that defines a 'Heavy Workload Day' for a teacher.")),
                        ('prevent_consecutive_heavy_days', models.BooleanField(default=True, help_text="If True, the auto-generator will heavily penalize giving a teacher two 'Heavy Days' in a row.")),
                    ],
                    options={
                        'db_table': 'school_timetablepedagogypolicy',
                    },
                ),
                migrations.CreateModel(
                    name='Timetable',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(help_text='e.g., Term 1 - November 2026', max_length=100)),
                        ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=20)),
                        ('is_active', models.BooleanField(default=False, help_text='Is this the currently running school timetable?')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school.academicyear')),
                        ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school.examterm')),
                    ],
                    options={
                        'db_table': 'school_timetable',
                    },
                ),
                migrations.CreateModel(
                    name='LessonAllocation',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('is_double_period', models.BooleanField(default=False)),
                        ('is_locked', models.BooleanField(default=False)),
                        ('class_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classstream')),
                        ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
                        ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacherextra')),
                        ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.timeslot')),
                        ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='timetable.timetable')),
                    ],
                    options={
                        'db_table': 'school_lessonallocation',
                        'unique_together': {('timetable', 'time_slot', 'class_stream', 'subject'), ('timetable', 'time_slot', 'teacher')},
                    },
                ),
                migrations.CreateModel(
                    name='DailyCover',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('date', models.DateField(help_text='The specific calendar day the cover is needed.')),
                        ('notes', models.TextField(blank=True, help_text="e.g., 'Sick leave', 'Attending seminar'", null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('absent_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='school.teacherextra')),
                        ('covering_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers_provided', to='school.teacherextra')),
                        ('target_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='timetable.lessonallocation')),
                    ],
                    options={
                        'db_table': 'school_dailycover',
                        'unique_together': {('date', 'target_lesson')},
                    },
                ),
            ],
        ),
    ]
