# Generated by Django 6.0.1 on 2026-08-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_permission_adminextra_admininvitecode_and_more'),
        ('timetable', '0002_alter_lessonallocation_class_stream_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='dailycover',
                    name='absent_teacher',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='identity.teacherextra'),
                ),
                migrations.AlterField(
                    model_name='dailycover',
                    name='covering_teacher',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers_provided', to='identity.teacherextra'),
                ),
                migrations.AlterField(
                    model_name='lessonallocation',
                    name='teacher',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.teacherextra'),
                ),
            ],
            database_operations=[]
        )
    ]
