# Generated by Django 6.0.7 on 2026-09-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_dailycover_absent_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Is this the currently running school timetable?'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], db_index=True, default='Draft', max_length=20),
        ),
    ]
