# Hand-written -- NOT autogenerated. Track B step 2: state-only relocation of
# BackgroundJob and SystemAuditLog into the `core` app. database_operations is
# empty in the SeparateDatabaseAndState wrapper below, so this migration issues
# zero SQL -- it only tells Django's migration state that these two models now
# belong to `core`. The physical tables (school_backgroundjob,
# school_systemauditlog, pinned via Meta.db_table in apps/core/models.py) never
# move. Paired with school/migrations/0092_move_core_models_to_apps_core.py,
# which deletes the same two models from `school`'s state, also with
# database_operations=[].
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='BackgroundJob',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('job_type', models.CharField(max_length=50)),
                        ('status', models.CharField(choices=[('PENDING', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Completed'), ('FAILURE', 'Failed')], default='PENDING', max_length=10)),
                        ('result', models.JSONField(blank=True, null=True)),
                        ('error_message', models.TextField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('completed_at', models.DateTimeField(blank=True, null=True)),
                        ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_jobs', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'school_backgroundjob',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='SystemAuditLog',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('action_type', models.CharField(choices=[('CREATE', 'Created Resource'), ('UPDATE', 'Modified Settings / Rules'), ('DELETE', 'Soft Deleted Resource'), ('RESTORE', 'Restored Soft Deleted Resource'), ('SIMULATION', 'Executed Allocation Simulation'), ('EXECUTION', 'Committed Live Allocation Splits'), ('APPROVE', 'Approved Pending Account'), ('REJECT', 'Rejected Pending Account'), ('AUTH_SUCCESS', 'Authentication Succeeded'), ('AUTH_FAILURE', 'Authentication Failed')], max_length=20)),
                        ('module', models.CharField(help_text="e.g., 'SplittingEngine', 'ClassStream'", max_length=100)),
                        ('description', models.TextField(help_text='Detailed summary of the operational event.')),
                        ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                        ('timestamp', models.DateTimeField(auto_now_add=True)),
                        ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'school_systemauditlog',
                        'ordering': ['-timestamp'],
                    },
                ),
            ],
        ),
    ]
