# Generated by Django 6.0.1 on 2026-09-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_backgroundjob_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemauditlog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Created Resource'), ('UPDATE', 'Modified Settings / Rules'), ('DELETE', 'Soft Deleted Resource'), ('RESTORE', 'Restored Soft Deleted Resource'), ('SIMULATION', 'Executed Allocation Simulation'), ('EXECUTION', 'Committed Live Allocation Splits'), ('APPROVE', 'Approved Pending Account'), ('REJECT', 'Rejected Pending Account'), ('PROMOTE', 'Promoted or Graduated Student'), ('AUTH_SUCCESS', 'Authentication Succeeded'), ('AUTH_FAILURE', 'Authentication Failed'), ('HARD_DELETE', 'Permanently Deleted Resource')], db_index=True, max_length=20),
        ),
    ]
