# Hand-written -- NOT autogenerated. Track B step 4: state-only relocation of
# AttendanceSession and AttendanceRecord into the `attendance` app.
# database_operations is empty, so this issues zero SQL -- it only tells
# Django's migration state that these two models now belong to `attendance`.
# The physical tables (pinned via Meta.db_table in apps/attendance/models.py)
# never move. The exact CreateModel field reprs below were taken verbatim
# from `manage.py makemigrations attendance assignments school --dry-run
# -v3` -- Django's own autodetector, not hand-transcribed. Paired with
# school/migrations/0094_move_attendance_assignments_models_to_apps.py, which
# deletes the same two models from `school`'s state, also with
# database_operations=[].
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0094_move_attendance_assignments_models_to_apps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='AttendanceSession',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('date', models.DateField()),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('class_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='school.classstream')),
                        ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'school_attendancesession',
                        'unique_together': {('class_stream', 'date')},
                    },
                ),
                migrations.CreateModel(
                    name='AttendanceRecord',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Excused', 'Excused')], default='Present', max_length=10)),
                        ('remarks', models.CharField(blank=True, help_text="e.g., 'Sick leave', 'Arrived at 9 AM'", max_length=255, null=True)),
                        ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='school.studentextra')),
                        ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession')),
                    ],
                    options={
                        'db_table': 'school_attendancerecord',
                        'unique_together': {('session', 'student')},
                    },
                ),
            ],
        ),
    ]
