# Generated by Django 6.0.1 on 2026-08-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancesession_class_stream'),
        ('identity', '0002_permission_adminextra_admininvitecode_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='attendancerecord',
                    name='student',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='identity.studentextra'),
                ),
            ],
            database_operations=[]
        )
    ]
