# Generated by Django 6.0.7 on 2026-09-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancerecord_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Excused', 'Excused')], db_index=True, default='Present', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
