# Hand-written -- NOT autogenerated. Track B step 4: state-only relocation of
# Assignment, AssignmentAttachment, AssignmentGroup, Question, QuestionOption,
# RubricCriterion, StudentSubmission, StudentAnswer, and CriterionScore into
# the `assignments` app. database_operations is empty, so this issues zero
# SQL -- it only tells Django's migration state that these 9 models now
# belong to `assignments`. The physical tables (pinned via Meta.db_table in
# apps/assignments/models.py) never move, including the 4 ManyToMany join
# tables (also pinned via db_table= on each M2M field). The exact
# CreateModel field reprs below were taken verbatim from
# `manage.py makemigrations attendance assignments school --dry-run -v3` --
# Django's own autodetector, not hand-transcribed -- to guarantee zero drift
# against `makemigrations --check`. Paired with
# school/migrations/0094_move_attendance_assignments_models_to_apps.py, which
# deletes the same 9 models from `school`'s state, also with
# database_operations=[].
import django.db.models.deletion
import school.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0094_move_attendance_assignments_models_to_apps'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Assignment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=255)),
                        ('assignment_type', models.CharField(choices=[('Holiday', 'Holiday Assignment'), ('In-Term', 'In-Term / Weekend Project')], default='Holiday', max_length=20)),
                        ('curriculum_type', models.CharField(default='CBC', max_length=10)),
                        ('strand_name', models.CharField(blank=True, help_text="e.g., 'Numbers', 'Measurement'", max_length=255, null=True)),
                        ('teacher_attachment', models.FileField(blank=True, help_text='Optional master PDF/Doc for the assignment', null=True, upload_to='assignments/teacher_files/', validators=[school.validators.safe_document_validator])),
                        ('publish_date', models.DateTimeField(blank=True, help_text='When students can first see and open this.', null=True)),
                        ('due_date', models.DateTimeField(blank=True, help_text='The official deadline. Submissions after this are marked LATE.', null=True)),
                        ('cutoff_date', models.DateTimeField(blank=True, help_text='The absolute lockout. No submissions accepted after this minute.', null=True)),
                        ('is_quiz', models.BooleanField(default=False, help_text='If True, turns this into a strictly timed assessment.')),
                        ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Time limit in minutes (e.g., 45)', null=True)),
                        ('status', models.CharField(choices=[('Draft', 'Draft - Hidden from students'), ('Published', 'Published - Visible and Active'), ('Closed', 'Closed - Past due date, no new submissions')], default='Draft', max_length=20)),
                        ('total_max_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Auto-tallied from questions', max_digits=5)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('allow_resubmission', models.BooleanField(default=False, help_text='If True, students may resubmit after their first submission.')),
                        ('max_attempts', models.PositiveIntegerField(default=1, help_text='Maximum number of submit attempts allowed per student.')),
                        ('late_penalty_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Flat percentage deducted from the awarded score when a submission is late.', max_digits=5)),
                        ('is_group_assignment', models.BooleanField(default=False, help_text="If True, one member's submission is shared across the whole group.")),
                        ('reference_links', models.JSONField(blank=True, default=list, help_text='List of {label, url} reference links for students.')),
                        ('reference_notes', models.TextField(blank=True, help_text='Free-text reference material / instructions.', null=True)),
                        ('additional_class_streams', models.ManyToManyField(blank=True, db_table='school_assignment_additional_class_streams', help_text='Extra class streams (beyond the primary class_stream) that also receive this assignment.', related_name='shared_assignments', to='school.classstream')),
                        ('assigned_students', models.ManyToManyField(blank=True, db_table='school_assignment_assigned_students', help_text='If set, only these students are assigned this work. If empty, the whole class_stream (and additional_class_streams) is targeted.', related_name='specific_assignments', to='school.studentextra')),
                        ('class_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='school.classstream')),
                        ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
                        ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_created', to='school.teacherextra')),
                        ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.examterm')),
                    ],
                    options={
                        'db_table': 'school_assignment',
                    },
                ),
                migrations.CreateModel(
                    name='AssignmentAttachment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('file', models.FileField(upload_to='assignments/teacher_files/extra/', validators=[school.validators.safe_document_validator])),
                        ('label', models.CharField(blank=True, max_length=255)),
                        ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                        ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assignments.assignment')),
                    ],
                    options={
                        'db_table': 'school_assignmentattachment',
                    },
                ),
                migrations.CreateModel(
                    name='AssignmentGroup',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=255)),
                        ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='assignments.assignment')),
                        ('members', models.ManyToManyField(blank=True, db_table='school_assignmentgroup_members', related_name='assignment_groups', to='school.studentextra')),
                    ],
                    options={
                        'db_table': 'school_assignmentgroup',
                    },
                ),
                migrations.CreateModel(
                    name='Question',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('question_text', models.TextField()),
                        ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice - Auto Graded'), ('CHECKBOX', 'Checkbox - Multi-Select Auto Graded'), ('SHORT_ANSWER', 'Short Answer - Exact Match Auto Graded'), ('ESSAY', 'Essay/Long Text - Manual Grade'), ('FILE_UPLOAD', 'File/Image Upload - Manual Grade')], max_length=20)),
                        ('is_auto_graded', models.BooleanField(default=False)),
                        ('max_score', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                        ('required_answers', models.PositiveIntegerField(blank=True, default=1, help_text='Used for CHECKBOX questions', null=True)),
                        ('exact_match_answer', models.CharField(blank=True, max_length=255, null=True)),
                        ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.assignment')),
                    ],
                    options={
                        'db_table': 'school_question',
                    },
                ),
                migrations.CreateModel(
                    name='QuestionOption',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('option_text', models.CharField(max_length=255)),
                        ('is_correct', models.BooleanField(default=False)),
                        ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assignments.question')),
                    ],
                    options={
                        'db_table': 'school_questionoption',
                    },
                ),
                migrations.CreateModel(
                    name='RubricCriterion',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('criterion_text', models.CharField(max_length=255)),
                        ('max_points', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                        ('order', models.PositiveIntegerField(default=0)),
                        ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_criteria', to='assignments.question')),
                    ],
                    options={
                        'db_table': 'school_rubriccriterion',
                        'ordering': ['order', 'id'],
                    },
                ),
                migrations.CreateModel(
                    name='StudentSubmission',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('started_at', models.DateTimeField(blank=True, help_text='Crucial for calculating Quiz duration.', null=True)),
                        ('submitted_at', models.DateTimeField(blank=True, null=True)),
                        ('is_late', models.BooleanField(default=False)),
                        ('attempt_number', models.PositiveIntegerField(default=1, help_text='Which submit attempt this is, for max_attempts enforcement.')),
                        ('student_attachment', models.FileField(blank=True, help_text='Optional PDF/Image uploaded by the student', null=True, upload_to='assignments/student_files/', validators=[school.validators.safe_document_validator])),
                        ('teacher_returned_file', models.FileField(blank=True, help_text='Optional annotated file sent back to the student', null=True, upload_to='assignments/returned_files/', validators=[school.validators.safe_document_validator])),
                        ('grading_status', models.CharField(choices=[('Pending', 'Pending - Auto-marked, waiting for manual review'), ('Graded', 'Graded (Draft) - Hidden from student'), ('Published', 'Published - Grades Released to Student'), ('Returned', 'Returned for Revision')], default='Pending', max_length=20)),
                        ('total_awarded_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                        ('overall_feedback', models.TextField(blank=True, null=True)),
                        ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                        ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='school.studentextra')),
                    ],
                    options={
                        'db_table': 'school_studentsubmission',
                        'unique_together': {('assignment', 'student')},
                    },
                ),
                migrations.CreateModel(
                    name='StudentAnswer',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('text_answer', models.TextField(blank=True, null=True)),
                        ('uploaded_file', models.FileField(blank=True, null=True, upload_to='assignment_submissions/', validators=[school.validators.safe_document_validator])),
                        ('awarded_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                        ('teacher_comment', models.CharField(blank=True, max_length=255, null=True)),
                        ('teacher_corrected_text', models.TextField(blank=True, null=True)),
                        ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.question')),
                        ('selected_options', models.ManyToManyField(blank=True, db_table='school_studentanswer_selected_options', to='assignments.questionoption')),
                        ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.studentsubmission')),
                    ],
                    options={
                        'db_table': 'school_studentanswer',
                    },
                ),
                migrations.CreateModel(
                    name='CriterionScore',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                        ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assignments.rubriccriterion')),
                        ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='assignments.studentanswer')),
                    ],
                    options={
                        'db_table': 'school_criterionscore',
                        'unique_together': {('answer', 'criterion')},
                    },
                ),
            ],
        ),
    ]
