# Hand-written -- NOT autogenerated. Track B step 8 side-effect -- see
# apps/allocations/migrations/0002_alter_allocationpublishstate_academic_year_and_more.py
# for the full explanation (same class of change: `to=` app_label update
# only, database_operations=[], zero SQL). Verbatim from
# `manage.py makemigrations academics --dry-run -v3`.
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='assignment',
                    name='additional_class_streams',
                    field=models.ManyToManyField(blank=True, db_table='school_assignment_additional_class_streams', help_text='Extra class streams (beyond the primary class_stream) that also receive this assignment.', related_name='shared_assignments', to='academics.classstream'),
                ),
                migrations.AlterField(
                    model_name='assignment',
                    name='class_stream',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.classstream'),
                ),
                migrations.AlterField(
                    model_name='assignment',
                    name='subject',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
                ),
                migrations.AlterField(
                    model_name='assignment',
                    name='term',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.examterm'),
                ),
            ],
        ),
    ]
