# Generated by Django 6.0.1 on 2026-08-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_additional_class_streams_and_more'),
        ('identity', '0002_permission_adminextra_admininvitecode_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='assignment',
                    name='assigned_students',
                    field=models.ManyToManyField(blank=True, db_table='school_assignment_assigned_students', help_text='If set, only these students are assigned this work. If empty, the whole class_stream (and additional_class_streams) is targeted.', related_name='specific_assignments', to='identity.studentextra'),
                ),
                migrations.AlterField(
                    model_name='assignment',
                    name='teacher',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_created', to='identity.teacherextra'),
                ),
                migrations.AlterField(
                    model_name='assignmentgroup',
                    name='members',
                    field=models.ManyToManyField(blank=True, db_table='school_assignmentgroup_members', related_name='assignment_groups', to='identity.studentextra'),
                ),
                migrations.AlterField(
                    model_name='studentsubmission',
                    name='student',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='identity.studentextra'),
                ),
            ],
            database_operations=[]
        )
    ]
