# Generated by Django 6.0.7 on 2026-09-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignment_deleted_at_assignment_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('Holiday', 'Holiday Assignment'), ('In-Term', 'In-Term / Weekend Project')], db_index=True, default='Holiday', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='The official deadline. Submissions after this are marked LATE.', null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft - Hidden from students'), ('Published', 'Published - Visible and Active'), ('Closed', 'Closed - Past due date, no new submissions')], db_index=True, default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_auto_graded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice - Auto Graded'), ('CHECKBOX', 'Checkbox - Multi-Select Auto Graded'), ('SHORT_ANSWER', 'Short Answer - Exact Match Auto Graded'), ('ESSAY', 'Essay/Long Text - Manual Grade'), ('FILE_UPLOAD', 'File/Image Upload - Manual Grade')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='is_correct',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='grading_status',
            field=models.CharField(choices=[('Pending', 'Pending - Auto-marked, waiting for manual review'), ('Graded', 'Graded (Draft) - Hidden from student'), ('Published', 'Published - Grades Released to Student'), ('Returned', 'Returned for Revision')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='is_late',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
