# Hand-written -- NOT autogenerated. Track B step 7: state-only relocation of
# GradingRule, ExamEvent, ClassExamStatus, ExamResult, and
# StudentReportSummary into the `exams` app. database_operations is empty,
# so this issues zero SQL -- it only tells Django's migration state that
# these five models now belong to `exams`. The physical tables (pinned via
# Meta.db_table in apps/exams/models.py) never move. The exact CreateModel
# field reprs below were taken verbatim from
# `manage.py makemigrations exams results school --dry-run -v3` -- Django's
# own autodetector, not hand-transcribed -- to guarantee zero drift against
# `makemigrations --check`. Paired with
# school/migrations/0097_move_exams_results_models_to_apps.py, which deletes
# the same five models from `school`'s state, also with
# database_operations=[].
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0097_move_exams_results_models_to_apps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='GradingRule',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('curriculum', models.CharField(choices=[('CBC', 'Competency Based Curriculum (CBC)'), ('8-4-4', 'Standard 8-4-4 Curriculum')], default='8-4-4', max_length=10)),
                        ('grade_label', models.CharField(help_text="e.g., 'A' or 'EE'", max_length=5)),
                        ('min_score', models.DecimalField(decimal_places=2, help_text='Minimum percentage/score', max_digits=5)),
                        ('max_score', models.DecimalField(decimal_places=2, help_text='Maximum percentage/score', max_digits=5)),
                        ('remarks', models.CharField(blank=True, help_text="e.g., 'Excellent', 'Exceeding Expectation'", max_length=100)),
                    ],
                    options={
                        'db_table': 'school_gradingrule',
                        'ordering': ['-min_score'],
                    },
                ),
                migrations.CreateModel(
                    name='ExamEvent',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(help_text='e.g., Term 1 CAT 1', max_length=100)),
                        ('exam_type', models.CharField(choices=[('CAT', 'Continuous Assessment Test'), ('MAIN', 'Main/End of Term Exam')], default='CAT', max_length=10)),
                        ('total_marks', models.IntegerField(default=100)),
                        ('status', models.CharField(choices=[('Draft', 'Draft - Teachers entering marks'), ('Submitted', 'Submitted - Waiting Admin Approval'), ('Published', 'Published - Visible to Students/Parents')], default='Draft', max_length=20)),
                        ('published_at', models.DateTimeField(blank=True, help_text='Timestamp of when the exam was published.', null=True)),
                        ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='school.examterm')),
                    ],
                    options={
                        'db_table': 'school_examevent',
                    },
                ),
                migrations.CreateModel(
                    name='ClassExamStatus',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('status', models.CharField(choices=[('Draft', 'Draft - Teachers entering marks'), ('Submitted', 'Submitted - Waiting Admin Approval'), ('Published', 'Published - Visible to Students/Parents')], default='Draft', max_length=20)),
                        ('published_at', models.DateTimeField(blank=True, null=True)),
                        ('class_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_publish_statuses', to='school.classstream')),
                        ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                        ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_publish_statuses', to='exams.examevent')),
                    ],
                    options={
                        'db_table': 'school_classexamstatus',
                        'unique_together': {('exam', 'class_stream')},
                    },
                ),
                migrations.CreateModel(
                    name='ExamResult',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                        ('teacher_remarks', models.CharField(blank=True, max_length=255, null=True)),
                        ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.examevent')),
                        ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='school.studentextra')),
                        ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
                        ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.teacherextra')),
                    ],
                    options={
                        'db_table': 'school_examresult',
                        'unique_together': {('exam', 'student', 'subject')},
                    },
                ),
                migrations.CreateModel(
                    name='StudentReportSummary',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('class_teacher_remark', models.TextField(blank=True, help_text='Manual remark from the class teacher', null=True)),
                        ('principal_remark', models.TextField(blank=True, help_text='Manual remark from the principal', null=True)),
                        ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_summaries', to='exams.examevent')),
                        ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_summaries', to='school.studentextra')),
                    ],
                    options={
                        'db_table': 'school_studentreportsummary',
                        'unique_together': {('student', 'exam')},
                    },
                ),
            ],
        ),
    ]
