# Hand-written -- NOT autogenerated. Track B step 8 side-effect -- see
# apps/allocations/migrations/0002_alter_allocationpublishstate_academic_year_and_more.py
# for the full explanation (same class of change: `to=` app_label update
# only, database_operations=[], zero SQL). Verbatim from
# `manage.py makemigrations academics --dry-run -v3`.
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='classexamstatus',
                    name='class_stream',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_publish_statuses', to='academics.classstream'),
                ),
                migrations.AlterField(
                    model_name='examevent',
                    name='term',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.examterm'),
                ),
                migrations.AlterField(
                    model_name='examresult',
                    name='subject',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
                ),
            ],
        ),
    ]
