# Generated by Django 6.0.1 on 2026-08-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_classexamstatus_class_stream_and_more'),
        ('identity', '0002_permission_adminextra_admininvitecode_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='examresult',
                    name='student',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='identity.studentextra'),
                ),
                migrations.AlterField(
                    model_name='examresult',
                    name='teacher',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.teacherextra'),
                ),
                migrations.AlterField(
                    model_name='studentreportsummary',
                    name='student',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_summaries', to='identity.studentextra'),
                ),
            ],
            database_operations=[]
        )
    ]
