# Generated by Django 6.0.7 on 2026-09-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_academicyear_is_active_and_more'),
        ('exams', '0003_alter_examresult_student_alter_examresult_teacher_and_more'),
        ('identity', '0009_alter_adminextra_mobile_alter_adminextra_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classexamstatus',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft - Teachers entering marks'), ('Submitted', 'Submitted - Waiting Admin Approval'), ('Published', 'Published - Visible to Students/Parents')], db_index=True, default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='examevent',
            name='exam_type',
            field=models.CharField(choices=[('CAT', 'Continuous Assessment Test'), ('MAIN', 'Main/End of Term Exam')], db_index=True, default='CAT', max_length=10),
        ),
        migrations.AlterField(
            model_name='examevent',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft - Teachers entering marks'), ('Submitted', 'Submitted - Waiting Admin Approval'), ('Published', 'Published - Visible to Students/Parents')], db_index=True, default='Draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam', 'subject'], name='examresult_exam_subject_idx'),
        ),
    ]
