"""
Admin invite-code generation/management and post-approval verification-code visibility.

Two distinct codes live here:
  - AdminInviteCode: required on /adminsignup for every non-bootstrap admin. Generated by an
    existing admin ahead of time and relayed out-of-band to whoever they're inviting.
  - AdminExtra.verification_code: generated when an existing admin clicks "Approve" on a
    pending admin application (see api_process_approval / _generate_admin_verification_code
    in school/views/views.py). This module only exposes status/regeneration for it, since the
    generation logic itself is shared with the approve step and lives there.
"""
import json
import secrets
from datetime import timedelta

from django.core.cache import cache
from django.http import JsonResponse
from django.utils import timezone

from apps.core.services import write_audit_log
from school.decorators import require_permission
from apps.identity.models import AdminExtra, AdminInviteCode
from school.views.auth_rate_limit import client_ip
from school.views.views import _generate_admin_verification_code

# Ambiguous characters (0/O, 1/I) are excluded so a code read aloud or typed by hand is
# unambiguous. 3 groups of 4 from this 32-symbol alphabet is ~60 bits of entropy.
_INVITE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
_ALLOWED_EXPIRY_DAYS = {1, 3, 7, 30}


def _generate_raw_invite_code():
    groups = [''.join(secrets.choice(_INVITE_ALPHABET) for _ in range(4)) for _ in range(3)]
    return '-'.join(groups)


@require_permission('admin_invites.manage')
def api_generate_admin_invite(request):
    if request.method != 'POST':
        return JsonResponse({'status': 'error', 'message': 'Invalid request method'}, status=405)

    try:
        data = json.loads(request.body or '{}')
    except json.JSONDecodeError:
        data = {}

    expires_in_days = data.get('expires_in_days', 7)
    if expires_in_days not in _ALLOWED_EXPIRY_DAYS:
        return JsonResponse({'status': 'error', 'message': 'expires_in_days must be one of 1, 3, 7, 30.'}, status=400)

    raw_code = _generate_raw_invite_code()
    invite = AdminInviteCode.objects.create(
        code_hash=AdminInviteCode.hash_code(raw_code),
        code_preview=raw_code[-4:],
        created_by=request.user,
        expires_at=timezone.now() + timedelta(days=expires_in_days),
    )
    write_audit_log(
        operator_id=request.user.id, action_type='CREATE', module='AdminInvite',
        description=f"Generated an admin signup invite code (ending ...{invite.code_preview}), expires in {expires_in_days} day(s).",
        ip_address=client_ip(request),
    )
    return JsonResponse({
        'status': 'success',
        'code': raw_code,
        'expires_at': invite.expires_at.isoformat(),
    })


@require_permission('admin_invites.manage')
def api_list_admin_invites(request):
    if request.method != 'GET':
        return JsonResponse({'status': 'error', 'message': 'Invalid request method'}, status=405)

    invites = AdminInviteCode.objects.select_related('created_by', 'used_by').all()
    data = [{
        'id': inv.id,
        'code_preview': inv.code_preview,
        'status': inv.status,
        'created_at': inv.created_at.isoformat(),
        'expires_at': inv.expires_at.isoformat(),
        'created_by': inv.created_by.get_full_name() or inv.created_by.username if inv.created_by else 'Unknown',
        'used_at': inv.used_at.isoformat() if inv.used_at else None,
        'used_by': (inv.used_by.get_full_name() or inv.used_by.username) if inv.used_by else None,
    } for inv in invites]
    return JsonResponse({'status': 'success', 'data': data})


@require_permission('admin_invites.manage')
def api_revoke_admin_invite(request, pk):
    if request.method != 'POST':
        return JsonResponse({'status': 'error', 'message': 'Invalid request method'}, status=405)

    try:
        invite = AdminInviteCode.objects.get(pk=pk)
    except AdminInviteCode.DoesNotExist:
        return JsonResponse({'status': 'error', 'message': 'Invite code not found.'}, status=404)

    if invite.status != 'Active':
        return JsonResponse({'status': 'error', 'message': f'Cannot revoke a code that is already {invite.status.lower()}.'}, status=400)

    invite.revoked_at = timezone.now()
    invite.revoked_by = request.user
    invite.save()
    write_audit_log(
        operator_id=request.user.id, action_type='DELETE', module='AdminInvite',
        description=f"Revoked admin signup invite code (ending ...{invite.code_preview}).",
        ip_address=client_ip(request),
    )
    return JsonResponse({'status': 'success'})


@require_permission('admin_invites.manage')
def api_admin_verification_status(request):
    if request.method != 'GET':
        return JsonResponse({'status': 'error', 'message': 'Invalid request method'}, status=405)

    pending = AdminExtra.objects.select_related('user').filter(
        status=False, verification_code__isnull=False
    ).order_by('code_generated_at')
    data = [{
        'id': ae.id,
        'name': ae.user.get_full_name() or ae.user.username,
        'email': ae.user.email,
        'username': ae.user.username,
        'code_generated_at': ae.code_generated_at.isoformat() if ae.code_generated_at else None,
        'expires_at': (ae.code_generated_at + timedelta(minutes=30)).isoformat() if ae.code_generated_at else None,
        'attempts_used': cache.get(f'verify_code_attempts:{ae.pk}', 0),
    } for ae in pending]
    return JsonResponse({'status': 'success', 'data': data})


@require_permission('admin_invites.manage')
def api_regenerate_admin_code(request, admin_extra_id):
    if request.method != 'POST':
        return JsonResponse({'status': 'error', 'message': 'Invalid request method'}, status=405)

    try:
        admin_extra = AdminExtra.objects.select_related('user').get(pk=admin_extra_id, status=False)
    except AdminExtra.DoesNotExist:
        return JsonResponse({'status': 'error', 'message': 'Pending admin not found.'}, status=404)

    code = _generate_admin_verification_code(
        admin_extra, request.user, request,
        f"Regenerated admin verification code for '{admin_extra.user.username}'.",
    )
    return JsonResponse({'status': 'success', 'verification_code': code})
